TweenEngineLib: Tween::ITweenable Class Reference
Tween::ITweenable Class Reference abstract
#include <ITweenable.h>
Public Member Functions
virtual ~ITweenable ()
Protected Member Functions
virtual void _GetValues (int _Type, float *_ReturnValues, uint8 _ucArraySize) const =0
virtual void _SetValues (int _Type, const float *_NewValues, uint8 _ucArraySize)=0
virtual int _GetValuesCount (int _Type) const =0
Friends
class BaseTween
class Tween
Detailed Description
Definition at line 11 of file ITweenable.h.
Constructor & Destructor Documentation
virtual Tween::ITweenable::~ITweenable () inline virtual
Definition at line 21 of file ITweenable.h.
{}
Member Function Documentation
virtual void Tween::ITweenable::_GetValues (int _Type, float * _ReturnValues, uint8 _ucArraySize) const protected pure virtual
Implemented in Tween::TweenableValue< T >.
Referenced by Tween::Tween::_InnerInitialize().
virtual int Tween::ITweenable::_GetValuesCount (int _Type) const protected pure virtual
Implemented in Tween::TweenableValue< T >.
Referenced by Tween::Tween::Setup().
virtual void Tween::ITweenable::_SetValues (int _Type, const float * _NewValues, uint8 _ucArraySize) protected pure virtual
Implemented in Tween::TweenableValue< T >.
Referenced by Tween::Tween::_ForceEndValues(), Tween::Tween::_ForceStartValues(), and Tween::Tween::_InnerUpdate().
Friends And Related Function Documentation
friend class BaseTween friend
Definition at line 19 of file ITweenable.h.
friend class Tween friend
Definition at line 20 of file ITweenable.h.
The documentation for this class was generated from the following file:
SRC/Tween/ITweenable.h