TweenEngineLib: Tween::Pool< T > Class Template Reference
Tween::Pool< T > Class Template Reference
#include <Pool.h>
Public Member Functions
Pool ()
~Pool ()
T * Get ()
void Free (T *_pObject)
Protected Member Functions
int _bContains (const std::vector< T * > &_vector, T *_pObject)
void _OnPool (T *_pObject)
void _OnUnPool (T *_pObject)
Private Attributes
std::vector< T * > m_InPool
std::vector< T * > m_OutOfPool
Detailed Description
template<class T>
class Tween::Pool< T >
Definition at line 13 of file Pool.h.
Constructor & Destructor Documentation
template<class T> Tween::Pool< T >::Pool () inline
Definition at line 17 of file Pool.h.
        {
        }
template<class T> Tween::Pool< T >::~Pool () inline
Definition at line 22 of file Pool.h.
        {
                size_t i;
                for(i = 0; i < m_InPool.size(); i++)
                {
                        T* pObject = m_InPool[i];
                        delete pObject;
                }
                m_InPool.clear();
                for(i = 0; i < m_OutOfPool.size(); i++)
                {
                        T* pObject = m_OutOfPool[i];
                        delete pObject;
                }
                m_OutOfPool.clear();
        }
Member Function Documentation
template<class T> int Tween::Pool< T >::_bContains (const std::vector< T * > & _vector, T * _pObject) inline protected
Definition at line 73 of file Pool.h.
Referenced by Tween::Pool< Timeline >::Free().
        {
                if(!_pObject)
                        return -1;
                for(size_t i = 0; i < _vector.size(); i++)
                {
                        if(_vector[i] == _pObject)
                                return (int)i;
                }
                return -1;
        }
template<class T> void Tween::Pool< T >::_OnPool (T * _pObject) inline protected
Definition at line 86 of file Pool.h.
Referenced by Tween::Pool< Timeline >::Free().
{}
template<class T> void Tween::Pool< T >::_OnUnPool (T * _pObject) inline protected
Definition at line 87 of file Pool.h.
Referenced by Tween::Pool< Timeline >::Get().
{}
template<class T> void Tween::Pool< T >::Free (T * _pObject) inline
Definition at line 56 of file Pool.h.
Referenced by Tween::Timeline::Free(), and Tween::Tween::Free().
        {
                if(_pObject)
                {
                        int outOfPoolIndex = _bContains(m_OutOfPool, _pObject);
                        if(outOfPoolIndex != -1 && _bContains(m_InPool, _pObject) == -1)
{
                                m_InPool.push_back(_pObject);
                                _OnPool(_pObject);
                                m_OutOfPool[outOfPoolIndex] = m_OutOfPool[m_OutOfPool.size() - 1];
                                m_OutOfPool.pop_back();
                        }
                }
        }
template<class T> T* Tween::Pool< T >::Get () inline
Definition at line 40 of file Pool.h.
Referenced by Tween::Timeline::BeginParallel(), Tween::Timeline::BeginSequence(), Tween::Tween::Call(), Tween::Tween::Mark(), Tween::Tween::Set(), and Tween::Tween::To().
        {
                T* pObject = NULL;
                if(m_InPool.empty())
                        pObject = new T();
                else
                {
                        pObject = m_InPool[m_InPool.size() - 1];
                        m_InPool.pop_back();
                }
                m_OutOfPool.push_back(pObject);
                _OnUnPool(pObject);
                return pObject;
        }
Member Data Documentation
template<class T> std::vector<T*> Tween::Pool< T >::m_InPool private
Definition at line 90 of file Pool.h.
Referenced by Tween::Pool< Timeline >::Free(), Tween::Pool< Timeline >::Get(), and Tween::Pool< Timeline >::~Pool().
template<class T> std::vector<T*> Tween::Pool< T >::m_OutOfPool private
Definition at line 91 of file Pool.h.
Referenced by Tween::Pool< Timeline >::Free(), Tween::Pool< Timeline >::Get(), and Tween::Pool< Timeline >::~Pool().
The documentation for this class was generated from the following files:
SRC/Tools/Pool.h
SRC/Tween/Timeline.cpp
SRC/Tween/Tween.cpp