TweenEngineLib: Tween::Manager Class Reference
Tween::Manager Class Reference
#include <Manager.h>
Public Member Functions
Manager ()
~Manager ()
bool bContainsTarget (ITweenable *_pTarget, uint8 _GroupID=MAX_GROUP_ID) const
bool bContainsTarget (ITweenable *_pTarget, int _iType, uint8 _GroupID=MAX_GROUP_ID) const
void KillAll ()
void KillTarget (ITweenable *_pTarget, uint8 _GroupID=MAX_GROUP_ID)
void KillTarget (ITweenable *_pTarget, int _iType, uint8 _GroupID=MAX_GROUP_ID)
void SetDtFactor (float _fFactor, uint8 _GroupID=MAX_GROUP_ID)
void Pause ()
void Resume ()
void Update (float _fDt)
Static Public Attributes
static const uint8 MAX_GROUP_ID = 0xFF
static const uint8 DEFAULT_GROUP_ID = 0
Protected Member Functions
void Register (BaseTween *_pTween, uint8 _GroupID=DEFAULT_GROUP_ID)
TweenGroup * GetGroupByID (uint8 _GroupID) const
TweenGroup * GetGroupByIndex (uint32 _uiIndex) const
Private Attributes
std::vector< TweenGroup * > m_TweenGroups
bool m_bPaused
Friends
class TweenGroup
class BaseTween
Detailed Description
Definition at line 16 of file Manager.h.
Constructor & Destructor Documentation
Tween::Manager::Manager ()
Definition at line 14 of file Manager.cpp.
: m_bPaused(false)
{
}
Tween::Manager::~Manager ()
Definition at line 21 of file Manager.cpp.
References GetGroupByIndex(), and m_TweenGroups.
{
        for(size_t i = 0; i < m_TweenGroups.size(); ++i)
        {
                TweenGroup* pGroup = GetGroupByIndex(i);
                delete pGroup;
        }
        m_TweenGroups.clear();
}
Member Function Documentation
bool Tween::Manager::bContainsTarget (ITweenable * _pTarget, uint8 _GroupID = MAX_GROUP_ID) const
Definition at line 70 of file Manager.cpp.
References Tween::TweenGroup::bContainsTarget(), GetGroupByID(), GetGroupByIndex(), m_TweenGroups, and MAX_GROUP_ID.
{
        if(_GroupID == MAX_GROUP_ID)
        {
                for(size_t i = 0; i < m_TweenGroups.size(); ++i)
                {
                        TweenGroup* pGroup = GetGroupByIndex(i);
                        if(pGroup->bContainsTarget(_pTarget))
                                return true;
                }
        }
        else
        {
                TweenGroup* pGroup = GetGroupByID(_GroupID);
                if(pGroup)
                        return pGroup->bContainsTarget(_pTarget);
        }
        return false;
}
bool Tween::Manager::bContainsTarget (ITweenable * _pTarget, int _iType, uint8 _GroupID = MAX_GROUP_ID) const
Definition at line 92 of file Manager.cpp.
References Tween::TweenGroup::bContainsTarget(), GetGroupByID(), GetGroupByIndex(), m_TweenGroups, and MAX_GROUP_ID.
{
        if(_GroupID == MAX_GROUP_ID)
        {
                for(size_t i = 0; i < m_TweenGroups.size(); ++i)
                {
                        TweenGroup* pGroup = GetGroupByIndex(i);
                        if(pGroup->bContainsTarget(_pTarget, _iType))
                                return true;
                }
        }
        else
        {
                TweenGroup* pGroup = GetGroupByID(_GroupID);
                if(pGroup)
                        return pGroup->bContainsTarget(_pTarget, _iType);
        }
        return false;
}
TweenGroup * Tween::Manager::GetGroupByID (uint8 _GroupID) const protected
Definition at line 51 of file Manager.cpp.
References GetGroupByIndex(), Tween::TweenGroup::GetID(), and m_TweenGroups.
Referenced by bContainsTarget(), KillTarget(), Register(), and SetDtFactor().
{
        for(size_t i = 0; i < m_TweenGroups.size(); ++i)
        {
                TweenGroup* pGroup = GetGroupByIndex(i);
                if(pGroup->GetID() == _GroupID)
                        return pGroup;
        }
        return NULL;
}
TweenGroup * Tween::Manager::GetGroupByIndex (uint32 _uiIndex) const protected
Definition at line 63 of file Manager.cpp.
References m_TweenGroups.
Referenced by bContainsTarget(), GetGroupByID(), KillAll(), KillTarget(), SetDtFactor(), Update(), and ~Manager().
{
        return m_TweenGroups.at(_uiIndex);
}
void Tween::Manager::KillAll ()
Definition at line 112 of file Manager.cpp.
References GetGroupByIndex(), Tween::TweenGroup::KillAll(), and m_TweenGroups.
{
        for(size_t i = 0; i < m_TweenGroups.size(); ++i)
        {
                TweenGroup* pGroup = GetGroupByIndex(i);
                pGroup->KillAll();
        }
}
void Tween::Manager::KillTarget (ITweenable * _pTarget, uint8 _GroupID = MAX_GROUP_ID)
Definition at line 121 of file Manager.cpp.
References GetGroupByID(), GetGroupByIndex(), Tween::TweenGroup::KillTarget(), m_TweenGroups, and MAX_GROUP_ID.
{
        if(_GroupID == MAX_GROUP_ID)
        {
                for(size_t i = 0; i < m_TweenGroups.size(); ++i)
                {
                        TweenGroup* pGroup = GetGroupByIndex(i);
                        pGroup->KillTarget(_pTarget);
                }
        }
        else
        {
                TweenGroup* pGroup = GetGroupByID(_GroupID);
                if(pGroup)
                        return pGroup->KillTarget(_pTarget);
        }
}
void Tween::Manager::KillTarget (ITweenable * _pTarget, int _iType, uint8 _GroupID = MAX_GROUP_ID)
Definition at line 139 of file Manager.cpp.
References GetGroupByID(), GetGroupByIndex(), Tween::TweenGroup::KillTarget(), m_TweenGroups, and MAX_GROUP_ID.
{
        if(_GroupID == MAX_GROUP_ID)
        {
                for(size_t i = 0; i < m_TweenGroups.size(); ++i)
                {
                        TweenGroup* pGroup = GetGroupByIndex(i);
                        pGroup->KillTarget(_pTarget, _iType);
                }
        }
        else
        {
                TweenGroup* pGroup = GetGroupByID(_GroupID);
                if(pGroup)
                        return pGroup->KillTarget(_pTarget, _iType);
        }
}
void Tween::Manager::Pause () inline
Definition at line 35 of file Manager.h.
References m_bPaused.
{ m_bPaused = true; }
void Tween::Manager::Register (BaseTween * _pTween, uint8 _GroupID = DEFAULT_GROUP_ID) protected
Definition at line 32 of file Manager.cpp.
References Tween::TweenGroup::bContains(), GetGroupByID(), m_TweenGroups, Tween::TweenGroup::Register(), and TweenGroup.
Referenced by Tween::BaseTween::_Start().
{
        TweenGroup* pGroup = GetGroupByID(_GroupID);
        if(!pGroup)
        {
                pGroup = new TweenGroup(_GroupID);
                if(pGroup)
                        m_TweenGroups.push_back(pGroup);
        }
        if(pGroup)
        {
                if(!pGroup->bContains(_pTween))
                        pGroup->Register(_pTween);
        }
}
void Tween::Manager::Resume () inline
Definition at line 36 of file Manager.h.
References m_bPaused.
{ m_bPaused = false; }
void Tween::Manager::SetDtFactor (float _fFactor, uint8 _GroupID = MAX_GROUP_ID)
Definition at line 158 of file Manager.cpp.
References GetGroupByID(), GetGroupByIndex(), m_TweenGroups, MAX_GROUP_ID, and Tween::TweenGroup::SetDtFactor().
{
        if(_GroupID == MAX_GROUP_ID)
        {
                for(size_t i = 0; i < m_TweenGroups.size(); ++i)
                {
                        TweenGroup* pGroup = GetGroupByIndex(i);
                        pGroup->SetDtFactor(_fFactor);
                }
        }
        else
        {
                TweenGroup* pGroup = GetGroupByID(_GroupID);
                if(pGroup)
                        return pGroup->SetDtFactor(_fFactor);
        }
}
void Tween::Manager::Update (float _fDt)
Definition at line 177 of file Manager.cpp.
References GetGroupByIndex(), m_bPaused, m_TweenGroups, and Tween::TweenGroup::Update().
{
        if(m_bPaused)
                return;
        for(size_t i = 0; i < m_TweenGroups.size(); ++i)
        {
                TweenGroup* pGroup = GetGroupByIndex(i);
                pGroup->Update(_fDt);
        }
}
Friends And Related Function Documentation
friend class BaseTween friend
Definition at line 23 of file Manager.h.
friend class TweenGroup friend
Definition at line 22 of file Manager.h.
Referenced by Register().
Member Data Documentation
const uint8 Tween::Manager::DEFAULT_GROUP_ID = 0 static
Definition at line 20 of file Manager.h.
bool Tween::Manager::m_bPaused private
Definition at line 46 of file Manager.h.
Referenced by Pause(), Resume(), and Update().
std::vector<TweenGroup*> Tween::Manager::m_TweenGroups private
Definition at line 45 of file Manager.h.
Referenced by bContainsTarget(), GetGroupByID(), GetGroupByIndex(), KillAll(), KillTarget(), Register(), SetDtFactor(), Update(), and ~Manager().
const uint8 Tween::Manager::MAX_GROUP_ID = 0xFF static
Definition at line 19 of file Manager.h.
Referenced by bContainsTarget(), KillTarget(), and SetDtFactor().
The documentation for this class was generated from the following files:
SRC/Tween/Manager.h
SRC/Tween/Manager.cpp