TweenEngineLib: Tween::Easing::BounceIn Class Reference
Tween::Easing::BounceIn Class Reference
#include <Bounce.h>
Public Member Functions
virtual float compute (float _t, float _b, float _c, float _d) const
virtual float compute (float _t, float _d) const
Detailed Description
Definition at line 13 of file Bounce.h.
Member Function Documentation
float Tween::Easing::BounceIn::compute (float _t, float _b, float _c, float _d) const virtual
Implements Tween::Easing::Easing.
Definition at line 14 of file Bounce.cpp.
References Tween::Easing::BounceOut::compute().
Referenced by Tween::Easing::BounceInOut::compute().
{
        BounceOut bounce;
        return _c - bounce.compute(_d-_t, 0.0f, _c, _d) + _b;
}
float Tween::Easing::BounceIn::compute (float _t, float _d) const virtual
Implements Tween::Easing::Easing.
Definition at line 21 of file Bounce.cpp.
References Tween::Easing::BounceOut::compute().
{
        BounceOut bounce;
        return 1.0f - bounce.compute(_d-_t, _d);
}
The documentation for this class was generated from the following files:
SRC/Equations/Bounce.h
SRC/Equations/Bounce.cpp