TweenEngineLib: Tween::Easing::BounceInOut Class Reference
Tween::Easing::BounceInOut Class Reference
#include <Bounce.h>
Public Member Functions
virtual float compute (float _t, float _b, float _c, float _d) const
virtual float compute (float _t, float _d) const
Detailed Description
Definition at line 33 of file Bounce.h.
Member Function Documentation
float Tween::Easing::BounceInOut::compute (float _t, float _b, float _c, float _d) const virtual
Implements Tween::Easing::Easing.
Definition at line 56 of file Bounce.cpp.
References Tween::Easing::BounceIn::compute(), and Tween::Easing::BounceOut::compute().
{
        if (_t < _d/2)
        {
                BounceIn bounce;
                return bounce.compute(_t*2, 0.0f, _c, _d) * 0.5f + _b;
        }
    else
        {
                BounceOut bounce;
                return bounce.compute(_t*2-_d, 0.0f, _c, _d) * 0.5f + _c*0.5f + _b;
        }
}
float Tween::Easing::BounceInOut::compute (float _t, float _d) const virtual
Implements Tween::Easing::Easing.
Definition at line 71 of file Bounce.cpp.
References Tween::Easing::BounceIn::compute(), and Tween::Easing::BounceOut::compute().
{
        if (_t < _d/2)
        {
                BounceIn bounce;
                return bounce.compute(_t*2,_d) * 0.5f;
        }
        else
        {
                BounceOut bounce;
                return bounce.compute(_t*2-_d, _d) * 0.5f + 0.5f ;
        }
}
The documentation for this class was generated from the following files:
SRC/Equations/Bounce.h
SRC/Equations/Bounce.cpp