TweenEngineLib: Tween::TweenGroup Class Reference
Tween::TweenGroup Class Reference
#include <TweenGroup.h>
Public Member Functions
TweenGroup (uint8 _ID)
~TweenGroup ()
bool bContainsTarget (ITweenable *_pTarget) const
bool bContainsTarget (ITweenable *_pTarget, int _iType) const
void KillAll ()
void KillTarget (ITweenable *_pTarget)
void KillTarget (ITweenable *_pTarget, int _iType)
void Pause ()
void Resume ()
void Update (float _fDt)
void SetDtFactor (float _fFactor)
Protected Member Functions
void Register (BaseTween *_pTween)
uint8 GetID () const
Private Member Functions
bool bContains (BaseTween *_pTween) const
Private Attributes
std::list< BaseTween * > m_Tweens
uint8 m_ID
float m_fDtFactor
bool m_bPaused
Friends
class Manager
class BaseTween
Detailed Description
Definition at line 16 of file TweenGroup.h.
Constructor & Destructor Documentation
Tween::TweenGroup::TweenGroup (uint8 _ID)
Definition at line 13 of file TweenGroup.cpp.
: m_bPaused(false)
, m_fDtFactor(1.0f)
, m_ID(_ID)
{
}
Tween::TweenGroup::~TweenGroup ()
Definition at line 22 of file TweenGroup.cpp.
References KillAll().
{
        KillAll();
}
Member Function Documentation
bool Tween::TweenGroup::bContains (BaseTween * _pTween) const private
Definition at line 35 of file TweenGroup.cpp.
References m_Tweens.
Referenced by Register(), and Tween::Manager::Register().
{
        std::list<BaseTween*>::const_iterator it = m_Tweens.begin();
        while(it != m_Tweens.end())
        {
                if(*it == _pTween)
                        return true;
                it++;
        }
        return false;
}
bool Tween::TweenGroup::bContainsTarget (ITweenable * _pTarget) const
Definition at line 50 of file TweenGroup.cpp.
References m_Tweens.
Referenced by Tween::Manager::bContainsTarget().
{
        std::list<BaseTween*>::const_iterator it = m_Tweens.begin();
        while(it != m_Tweens.end())
        {
                if((*it)->_bContainsTarget(_pTarget))
                        return true;
                it++;
        }
        return false;
}
bool Tween::TweenGroup::bContainsTarget (ITweenable * _pTarget, int _iType) const
Definition at line 65 of file TweenGroup.cpp.
References m_Tweens.
{
        std::list<BaseTween*>::const_iterator it = m_Tweens.begin();
        while(it != m_Tweens.end())
        {
                if((*it)->_bContainsTarget(_pTarget, _iType))
                        return true;
                it++;
        }
        return false;
}
uint8 Tween::TweenGroup::GetID () const inline protected
Definition at line 37 of file TweenGroup.h.
References m_ID.
Referenced by Tween::Manager::GetGroupByID().
{ return m_ID; }
void Tween::TweenGroup::KillAll ()
Definition at line 79 of file TweenGroup.cpp.
References m_Tweens.
Referenced by Tween::Manager::KillAll(), and ~TweenGroup().
{
        std::list<BaseTween*>::iterator it = m_Tweens.begin();
        while(it != m_Tweens.end())
        {
                (*it)->Kill();
                it++;
        }
}
void Tween::TweenGroup::KillTarget (ITweenable * _pTarget)
Definition at line 89 of file TweenGroup.cpp.
References m_Tweens.
Referenced by Tween::Manager::KillTarget().
{
        std::list<BaseTween*>::iterator it = m_Tweens.begin();
        while(it != m_Tweens.end())
        {
                (*it)->_KillTarget(_pTarget);
                it++;
        }
}
void Tween::TweenGroup::KillTarget (ITweenable * _pTarget, int _iType)
Definition at line 99 of file TweenGroup.cpp.
References m_Tweens.
{
        std::list<BaseTween*>::iterator it = m_Tweens.begin();
        while(it != m_Tweens.end())
        {
                (*it)->_KillTarget(_pTarget, _iType);
                it++;
        }
}
void Tween::TweenGroup::Pause () inline
Definition at line 30 of file TweenGroup.h.
References m_bPaused.
{ m_bPaused = true; }
void Tween::TweenGroup::Register (BaseTween * _pTween) protected
Definition at line 28 of file TweenGroup.cpp.
References bContains(), and m_Tweens.
Referenced by Tween::Manager::Register().
{
        if(!bContains(_pTween))
                m_Tweens.push_back(_pTween);
}
void Tween::TweenGroup::Resume () inline
Definition at line 31 of file TweenGroup.h.
References m_bPaused.
{ m_bPaused = false; }
void Tween::TweenGroup::SetDtFactor (float _fFactor) inline
Definition at line 33 of file TweenGroup.h.
References m_fDtFactor.
Referenced by Tween::Manager::SetDtFactor().
{ m_fDtFactor = _fFactor; }
void Tween::TweenGroup::Update (float _fDt)
Definition at line 109 of file TweenGroup.cpp.
References Tween::BaseTween::bIsFinished(), m_bPaused, m_fDtFactor, and m_Tweens.
Referenced by Tween::Manager::Update().
{
        if(!m_Tweens.empty())
        {
                std::list<BaseTween*>::iterator it = m_Tweens.begin();
                while(it != m_Tweens.end())
                {
                        BaseTween* pTween = (*it);
                        if(pTween->bIsFinished())
{
                                it = m_Tweens.erase(it);
                        }
                        else
                                it++;
                }
        }
        if (!m_bPaused && !m_Tweens.empty())
        {
                _fDt *= m_fDtFactor;
                if (_fDt >= 0)
                {
                        std::list<BaseTween*>::iterator it = m_Tweens.begin();
                        while(it != m_Tweens.end())
{
                                (*it)->Update(_fDt);
                                it++;
                        }
                }
                else
                {
                        std::list<BaseTween*>::reverse_iterator it = m_Tweens.rbegin();
                        while(it != m_Tweens.rend())
{
                                (*it)->Update(_fDt);
                                it++;
                        }
                }
        }
}
Friends And Related Function Documentation
friend class BaseTween friend
Definition at line 20 of file TweenGroup.h.
friend class Manager friend
Definition at line 19 of file TweenGroup.h.
Member Data Documentation
bool Tween::TweenGroup::m_bPaused private
Definition at line 46 of file TweenGroup.h.
Referenced by Pause(), Resume(), and Update().
float Tween::TweenGroup::m_fDtFactor private
Definition at line 45 of file TweenGroup.h.
Referenced by SetDtFactor(), and Update().
uint8 Tween::TweenGroup::m_ID private
Definition at line 44 of file TweenGroup.h.
Referenced by GetID().
std::list<BaseTween*> Tween::TweenGroup::m_Tweens private
Definition at line 43 of file TweenGroup.h.
Referenced by bContains(), bContainsTarget(), KillAll(), KillTarget(), Register(), and Update().
The documentation for this class was generated from the following files:
SRC/Tween/TweenGroup.h
SRC/Tween/TweenGroup.cpp