TweenEngineLib: Tween::BitField< _Mask > Class Template Reference
Tween::BitField< _Mask > Class Template Reference
#include <BitField.h>
Public Types
typedef _Mask MaskType
Public Member Functions
BitField ()
BitField (_Mask _mask)
bool bTestMask (const _Mask &_ToTest) const
bool bTestMaskAny (const _Mask &_ToTest) const
bool bTestMask (const _Mask &_Mandatory, const _Mask &_AtLeastOne, const _Mask &_Exclude) const
void AddMask (const _Mask &_ToAdd)
void SubMask (const _Mask &_ToSub)
void Reset ()
_Mask GetMask () const
_Mask & Mask ()
void SetMask (_Mask _Val)
void ChangeMask (_Mask _Val, bool _On)
_Mask FlagToMask (uint8 _Flag) const
Flag should be a value between 0 and BitCount(_Mask), do not use shifted values.
bool bTestFlag (uint8 _Flag) const
Flag should be a value between 0 and BitCount(_Mask), do not use shifted values.
void AddFlag (uint8 _Flag)
Flag should be a value between 0 and BitCount(_Mask), do not use shifted values.
void SubFlag (uint8 _Flag)
Flag should be a value between 0 and BitCount(_Mask), do not use shifted values.
void ChangeFlag (uint8 _Flag, bool _On)
Flag should be a value between 0 and BitCount(_Mask), do not use shifted values.
Private Attributes
_Mask m_Mask
Detailed Description
template<class _Mask>
class Tween::BitField< _Mask >
Definition at line 7 of file BitField.h.
Member Typedef Documentation
template<class _Mask> typedef _Mask Tween::BitField< _Mask >::MaskType
Definition at line 110 of file BitField.h.
Constructor & Destructor Documentation
template<class _Mask> Tween::BitField< _Mask >::BitField () inline
Definition at line 10 of file BitField.h.
                : m_Mask(0)
        {
        }
template<class _Mask> Tween::BitField< _Mask >::BitField (_Mask _mask) inline
Definition at line 15 of file BitField.h.
        : m_Mask(_mask)
    {
    }
Member Function Documentation
template<class _Mask> void Tween::BitField< _Mask >::AddFlag (uint8 _Flag) inline
Flag should be a value between 0 and BitCount(_Mask), do not use shifted values.
Definition at line 90 of file BitField.h.
        {
                AddMask(FlagToMask(_Flag));
        }
template<class _Mask> void Tween::BitField< _Mask >::AddMask (const _Mask & _ToAdd) inline
Definition at line 38 of file BitField.h.
Referenced by Tween::BitField< uint8 >::AddFlag(), Tween::BitField< uint8 >::ChangeFlag(), Tween::BitField< uint8 >::ChangeMask(), Tween::BaseTween::Kill(), and Tween::BaseTween::Pause().
        {
                m_Mask |= _ToAdd;
        }
template<class _Mask> bool Tween::BitField< _Mask >::bTestFlag (uint8 _Flag) const inline
Flag should be a value between 0 and BitCount(_Mask), do not use shifted values.
Definition at line 84 of file BitField.h.
        {
                return bTestMask(FlagToMask(_Flag));
        }
template<class _Mask> bool Tween::BitField< _Mask >::bTestMask (const _Mask & _ToTest) const inline
Definition at line 21 of file BitField.h.
Referenced by Tween::BaseTween::_bIsIterationStep(), Tween::BaseTween::_bIsKilled(), Tween::BaseTween::bIsFinished(), Tween::BaseTween::bIsInit(), Tween::BaseTween::bIsPaused(), Tween::BaseTween::bIsStarted(), Tween::BaseTween::bIsYoyo(), Tween::BitField< uint8 >::bTestFlag(), and Tween::BitField< uint8 >::bTestMask().
        {
                return (m_Mask & _ToTest) == _ToTest;
        }
template<class _Mask> bool Tween::BitField< _Mask >::bTestMask (const _Mask & _Mandatory, const _Mask & _AtLeastOne, const _Mask & _Exclude) const inline
Definition at line 32 of file BitField.h.
        {
                bool bRet = bTestMask(_Mandatory) && (( m_Mask & _Exclude) == 0) && ( (!_AtLeastOne) || ((m_Mask & _AtLeastOne) > 0) );
                return bRet;
        }
template<class _Mask> bool Tween::BitField< _Mask >::bTestMaskAny (const _Mask & _ToTest) const inline
Definition at line 27 of file BitField.h.
    {
        return (m_Mask & _ToTest) != 0;
    }
template<class _Mask> void Tween::BitField< _Mask >::ChangeFlag (uint8 _Flag, bool _On) inline
Flag should be a value between 0 and BitCount(_Mask), do not use shifted values.
Definition at line 102 of file BitField.h.
        {
                if (_On)
                        AddMask(FlagToMask(_Flag));
                else
                        SubMask(FlagToMask(_Flag));
        }
template<class _Mask> void Tween::BitField< _Mask >::ChangeMask (_Mask _Val, bool _On) inline
Definition at line 68 of file BitField.h.
Referenced by Tween::BaseTween::_ForceToEnd(), Tween::BaseTween::_ForceToStart(), Tween::BaseTween::_Initialize(), Tween::BaseTween::_Repeat(), Tween::BaseTween::_Start(), Tween::BaseTween::_UpdateCompletion(), Tween::BaseTween::_UpdateRelaunch(), and Tween::BaseTween::_UpdateStep().
        {
                if (_On)
                        AddMask(_Val);
                else
                        SubMask(_Val);
        }
template<class _Mask> _Mask Tween::BitField< _Mask >::FlagToMask (uint8 _Flag) const inline
Flag should be a value between 0 and BitCount(_Mask), do not use shifted values.
Definition at line 78 of file BitField.h.
Referenced by Tween::BitField< uint8 >::AddFlag(), Tween::BitField< uint8 >::bTestFlag(), Tween::BitField< uint8 >::ChangeFlag(), and Tween::BitField< uint8 >::SubFlag().
        {
                return (_Mask)1ll<<_Flag;
        }
template<class _Mask> _Mask Tween::BitField< _Mask >::GetMask () const inline
Definition at line 53 of file BitField.h.
        {
                return m_Mask;
        }
template<class _Mask> _Mask& Tween::BitField< _Mask >::Mask () inline
Definition at line 58 of file BitField.h.
    {
        return m_Mask;
    }
template<class _Mask> void Tween::BitField< _Mask >::Reset () inline
Definition at line 48 of file BitField.h.
Referenced by Tween::BaseTween::_Reset().
        {
                m_Mask = 0;
        }
template<class _Mask> void Tween::BitField< _Mask >::SetMask (_Mask _Val) inline
Definition at line 63 of file BitField.h.
        {
                m_Mask = _Val;
        }
template<class _Mask> void Tween::BitField< _Mask >::SubFlag (uint8 _Flag) inline
Flag should be a value between 0 and BitCount(_Mask), do not use shifted values.
Definition at line 96 of file BitField.h.
        {
                SubMask(FlagToMask(_Flag));
        }
template<class _Mask> void Tween::BitField< _Mask >::SubMask (const _Mask & _ToSub) inline
Definition at line 43 of file BitField.h.
Referenced by Tween::BitField< uint8 >::ChangeFlag(), Tween::BitField< uint8 >::ChangeMask(), Tween::BaseTween::Resume(), and Tween::BitField< uint8 >::SubFlag().
        {
                m_Mask &= ~(_ToSub);
        }
Member Data Documentation
template<class _Mask> _Mask Tween::BitField< _Mask >::m_Mask private
Definition at line 113 of file BitField.h.
Referenced by Tween::BitField< uint8 >::AddMask(), Tween::BitField< uint8 >::bTestMask(), Tween::BitField< uint8 >::bTestMaskAny(), Tween::BitField< uint8 >::GetMask(), Tween::BitField< uint8 >::Mask(), Tween::BitField< uint8 >::Reset(), Tween::BitField< uint8 >::SetMask(), and Tween::BitField< uint8 >::SubMask().
The documentation for this class was generated from the following file:
SRC/Tools/BitField.h