TweenEngineLib: Tween::BaseTween Class Reference
Tween::BaseTween Class Reference abstract
#include <BaseTween.h>
Public Member Functions
BaseTween ()
virtual ~BaseTween ()
float fGetDelay () const
float fGetDuration () const
float fGetFullDuration () const
float fGetRepeatDelay () const
float fGetCurrentTime () const
int iGetRepeatCount () const
bool bIsStarted () const
bool bIsInit () const
bool bIsFinished () const
bool bIsYoyo () const
bool bIsPaused () const
void Kill ()
void Pause ()
void Resume ()
void Update (float _fDt)
virtual void Free ()
Protected Member Functions
virtual void _ForceStartValues ()=0
virtual void _ForceEndValues ()=0
virtual bool _bContainsTarget (ITweenable *_pTarget) const =0
virtual bool _bContainsTarget (ITweenable *_pTarget, int _iType) const =0
void _KillTarget (ITweenable *_pTarget)
void _KillTarget (ITweenable *_pTarget, int _iType)
virtual void _Reset ()
bool _bIsReverse (int _iStep) const
void _ForceToStart ()
void _ForceToEnd (float _fTime)
void _CallCallback (ITweenListener::EEventType _eType)
virtual void _InnerInitialize ()
virtual void _InnerUpdate (int _iStep, int _iLastStep, bool _bIsIterationStep, float _fDt)
virtual void _Build ()
virtual void _Start ()
void _Start (Manager *_pManager)
void _Start (Manager *_pManager, uint8 _GroupID)
void _Delay (float _fDelay)
void _Repeat (int _Count, float _fDelay, bool _bYoyo=false)
void _SetListener (ITweenListener *_pListener, int _iID=-1, int _iTriggers=ITweenListener::eComplete)
Protected Attributes
float m_fDelay
float m_fDuration
Private Types
enum eBaseTweenFlags {
eIsStarted = (1<<0), eIsInit = (1<<1), eIsFinished = (1<<2), eIsPaused = (1<<3),
eIsKilled = (1<<4), eIsYoyo = (1<<5), eIsIterationStep = (1<<6)
}
Private Member Functions
bool _bIsKilled () const
bool _bIsIterationStep () const
void _Initialize ()
void _UpdateRelaunch ()
void _UpdateStep ()
void _UpdateCompletion ()
bool _bIsValid (const int &_iStep) const
Private Attributes
ITweenListener * m_pListener
int m_iListenerTriggers
int m_iListenerID
int m_iStep
int m_iRepeatCount
float m_fRepeatDelay
float m_fCurrentTime
float m_fDt
BitField< uint8 > m_Flags
Friends
class TweenGroup
class Manager
class Timeline
Detailed Description
Definition at line 17 of file BaseTween.h.
Member Enumeration Documentation
enum Tween::BaseTween::eBaseTweenFlags private
Enumerator:
eIsStarted
eIsInit
eIsFinished
eIsPaused
eIsKilled
eIsYoyo
eIsIterationStep
Definition at line 111 of file BaseTween.h.
        {
                eIsStarted                      = (1<<0),
                eIsInit                         = (1<<1),
                eIsFinished                     = (1<<2),
                eIsPaused                       = (1<<3),
                eIsKilled                       = (1<<4),
                eIsYoyo                         = (1<<5),
                eIsIterationStep        = (1<<6),
        };
Constructor & Destructor Documentation
Tween::BaseTween::BaseTween ()
Definition at line 12 of file BaseTween.cpp.
: m_fDelay(0.0f)
, m_fDuration(0.0f)
, m_fRepeatDelay(0.0f)
, m_fCurrentTime(0.0f)
, m_iStep(-2)
, m_iRepeatCount(0)
, m_pListener(NULL)
, m_iListenerTriggers(0)
, m_iListenerID(0)
, m_fDt(0.0f)
{
}
virtual Tween::BaseTween::~BaseTween () inline virtual
Definition at line 25 of file BaseTween.h.
{}
Member Function Documentation
virtual bool Tween::BaseTween::_bContainsTarget (ITweenable * _pTarget) const protected pure virtual
Implemented in Tween::Tween, and Tween::Timeline.
Referenced by Tween::Timeline::_bContainsTarget(), and _KillTarget().
virtual bool Tween::BaseTween::_bContainsTarget (ITweenable * _pTarget, int _iType) const protected pure virtual
Implemented in Tween::Tween, and Tween::Timeline.
bool Tween::BaseTween::_bIsIterationStep () const inline private
Definition at line 40 of file BaseTween.h.
References Tween::BitField< _Mask >::bTestMask(), eIsIterationStep, and m_Flags.
Referenced by _UpdateRelaunch(), and _UpdateStep().
{ return m_Flags.bTestMask(eIsIterationStep);   }
bool Tween::BaseTween::_bIsKilled () const inline private
Definition at line 39 of file BaseTween.h.
References Tween::BitField< _Mask >::bTestMask(), eIsKilled, and m_Flags.
Referenced by Update().
{ return m_Flags.bTestMask(eIsKilled);          }
bool Tween::BaseTween::_bIsReverse (int _iStep) const inline protected
Definition at line 63 of file BaseTween.h.
References bIsYoyo().
Referenced by _ForceToEnd(), _ForceToStart(), Tween::Timeline::_InnerUpdate(), Tween::Tween::_InnerUpdate(), and _UpdateStep().
{
                                return bIsYoyo() && (abs(_iStep%4) == 2);
                        }
bool Tween::BaseTween::_bIsValid (const int & _iStep) const inline private
Definition at line 90 of file BaseTween.h.
References m_iRepeatCount.
Referenced by _UpdateStep().
{
                                return (_iStep >= 0 && _iStep <= m_iRepeatCount*2) || m_iRepeatCount < 0;
                        }
virtual void Tween::BaseTween::_Build () inline protected virtual
Reimplemented in Tween::Tween, and Tween::Timeline.
Definition at line 75 of file BaseTween.h.
Referenced by Tween::Timeline::_Build(), _Start(), and Tween::TemplatedTween< Timeline >::Build().
{}
void Tween::BaseTween::_CallCallback (ITweenListener::EEventType _eType) protected
Definition at line 107 of file BaseTween.cpp.
References m_iListenerID, m_iListenerTriggers, m_pListener, and Tween::ITweenListener::OnEvent().
Referenced by _Initialize(), _UpdateRelaunch(), and _UpdateStep().
{
        if (m_pListener && (m_iListenerTriggers & _eType) > 0)
                m_pListener->OnEvent(_eType, m_iListenerID);
}
void Tween::BaseTween::_Delay (float _fDelay) protected
Definition at line 142 of file BaseTween.cpp.
References m_fDelay.
Referenced by Tween::Timeline::_Build(), and Tween::TemplatedTween< Timeline >::Delay().
{
        m_fDelay += _fDelay;
}
virtual void Tween::BaseTween::_ForceEndValues () protected pure virtual
Implemented in Tween::Tween, and Tween::Timeline.
Referenced by _ForceToEnd(), _ForceToStart(), and _UpdateStep().
virtual void Tween::BaseTween::_ForceStartValues () protected pure virtual
Implemented in Tween::Tween, and Tween::Timeline.
Referenced by _ForceToEnd(), _ForceToStart(), and _UpdateStep().
void Tween::BaseTween::_ForceToEnd (float _fTime) protected
Definition at line 94 of file BaseTween.cpp.
References _bIsReverse(), _ForceEndValues(), _ForceStartValues(), Tween::BitField< _Mask >::ChangeMask(), eIsIterationStep, fGetFullDuration(), m_fCurrentTime, m_Flags, m_iRepeatCount, and m_iStep.
Referenced by Tween::Timeline::_ForceEndValues().
{
        m_fCurrentTime = _fTime - fGetFullDuration();
        m_iStep = m_iRepeatCount*2 + 1;
        m_Flags.ChangeMask(eIsIterationStep, false);
        if(_bIsReverse(m_iRepeatCount*2))
                _ForceStartValues();
        else
                _ForceEndValues();
}
void Tween::BaseTween::_ForceToStart () protected
Definition at line 80 of file BaseTween.cpp.
References _bIsReverse(), _ForceEndValues(), _ForceStartValues(), Tween::BitField< _Mask >::ChangeMask(), eIsIterationStep, m_fCurrentTime, m_fDelay, m_Flags, and m_iStep.
Referenced by Tween::Timeline::_ForceStartValues().
{
        m_fCurrentTime = -m_fDelay;
        m_iStep = -1;
        m_Flags.ChangeMask(eIsIterationStep, false);
        if(_bIsReverse(0))
                _ForceEndValues();
        else
                _ForceStartValues();
}
void Tween::BaseTween::_Initialize () private
Definition at line 167 of file BaseTween.cpp.
References _CallCallback(), _InnerInitialize(), Tween::BitField< _Mask >::ChangeMask(), Tween::ITweenListener::eBegin, eIsInit, eIsIterationStep, Tween::ITweenListener::eStart, m_fCurrentTime, m_fDelay, m_fDt, m_Flags, and m_iStep.
Referenced by Update().
{
        if(m_fCurrentTime + m_fDt >= m_fDelay)
        {
                _InnerInitialize();
                m_Flags.ChangeMask(eIsInit, true);
                m_Flags.ChangeMask(eIsIterationStep, true);
                m_iStep = 0;
                m_fDt -= m_fDelay - m_fCurrentTime;
                m_fCurrentTime = 0.0f;
                _CallCallback(ITweenListener::eBegin);
                _CallCallback(ITweenListener::eStart);
        }
}
virtual void Tween::BaseTween::_InnerInitialize () inline protected virtual
Reimplemented in Tween::Tween.
Definition at line 73 of file BaseTween.h.
Referenced by _Initialize().
{}
virtual void Tween::BaseTween::_InnerUpdate (int _iStep, int _iLastStep, bool _bIsIterationStep, float _fDt) inline protected virtual
Reimplemented in Tween::Tween, and Tween::Timeline.
Definition at line 74 of file BaseTween.h.
Referenced by _UpdateRelaunch(), and _UpdateStep().
{}
void Tween::BaseTween::_KillTarget (ITweenable * _pTarget) protected
Definition at line 50 of file BaseTween.cpp.
References _bContainsTarget(), and Kill().
{
        if(_bContainsTarget(_pTarget))
                Kill();
}
void Tween::BaseTween::_KillTarget (ITweenable * _pTarget, int _iType) protected
Definition at line 57 of file BaseTween.cpp.
References _bContainsTarget(), and Kill().
{
        if(_bContainsTarget(_pTarget, _iType))
                Kill();
}
void Tween::BaseTween::_Repeat (int _Count, float _fDelay, bool _bYoyo = false) protected
Definition at line 148 of file BaseTween.cpp.
References bIsStarted(), Tween::BitField< _Mask >::ChangeMask(), eIsYoyo, m_Flags, m_fRepeatDelay, and m_iRepeatCount.
Referenced by Tween::TemplatedTween< Timeline >::Repeat().
{
        if(!bIsStarted())
        {
                m_iRepeatCount = _Count;
                m_fRepeatDelay = (_fDelay > 0.0f)? _fDelay : 0.0f;
                m_Flags.ChangeMask(eIsYoyo, _bYoyo);
        }
}
void Tween::BaseTween::_Reset () protected virtual
Reimplemented in Tween::Tween, and Tween::Timeline.
Definition at line 64 of file BaseTween.cpp.
References m_fCurrentTime, m_fDelay, m_fDt, m_fDuration, m_Flags, m_fRepeatDelay, m_iRepeatCount, m_iStep, and Tween::BitField< _Mask >::Reset().
Referenced by Tween::Timeline::_Reset(), and Tween::Tween::_Reset().
{
        m_iStep = -2;
        m_iRepeatCount = 0;
        m_fDelay = 0.0f;
        m_fDuration = 0.0f;
        m_fRepeatDelay = 0.0f;
        m_fCurrentTime = 0.0f;
        m_fDt = 0.0f;
        m_Flags.Reset();
}
void Tween::BaseTween::_SetListener (ITweenListener * _pListener, int _iID = -1, int _iTriggers = ITweenListener::eComplete) protected
Definition at line 159 of file BaseTween.cpp.
References m_iListenerID, m_iListenerTriggers, and m_pListener.
Referenced by Tween::TemplatedTween< Timeline >::SetListener().
{
        m_pListener = _pListener;
        m_iListenerTriggers = _iTriggers;
        m_iListenerID = _iID;
}
void Tween::BaseTween::_Start () protected virtual
Reimplemented in Tween::Timeline.
Definition at line 114 of file BaseTween.cpp.
References _Build(), Tween::BitField< _Mask >::ChangeMask(), eIsStarted, m_fCurrentTime, and m_Flags.
Referenced by Tween::Timeline::_Start(), _Start(), and Tween::TemplatedTween< Timeline >::Start().
{
        _Build();
        m_fCurrentTime = 0.0f;
        m_Flags.ChangeMask(eIsStarted, true);
}
void Tween::BaseTween::_Start (Manager * _pManager) protected
Definition at line 122 of file BaseTween.cpp.
References _Start(), and Tween::Manager::Register().
{
        if(_pManager)
        {
                _pManager->Register(this);
                _Start();
        }
}
void Tween::BaseTween::_Start (Manager * _pManager, uint8 _GroupID) protected
Definition at line 132 of file BaseTween.cpp.
References _Start(), and Tween::Manager::Register().
{
        if(_pManager)
        {
                _pManager->Register(this, _GroupID);
                _Start();
        }
}
void Tween::BaseTween::_UpdateCompletion () private
Definition at line 290 of file BaseTween.cpp.
References Tween::BitField< _Mask >::ChangeMask(), eIsFinished, m_Flags, m_iRepeatCount, and m_iStep.
Referenced by Update().
{
        bool isFinished = (m_iRepeatCount >= 0 && (m_iStep > m_iRepeatCount*2 ||  m_iStep < 0));
        m_Flags.ChangeMask(eIsFinished, isFinished);
}
void Tween::BaseTween::_UpdateRelaunch () private
Definition at line 184 of file BaseTween.cpp.
References _bIsIterationStep(), _CallCallback(), _InnerUpdate(), Tween::BitField< _Mask >::ChangeMask(), Tween::ITweenListener::eBackBegin, Tween::ITweenListener::eBackStart, Tween::ITweenListener::eBegin, eIsIterationStep, Tween::ITweenListener::eStart, m_fCurrentTime, m_fDt, m_fDuration, m_Flags, m_iRepeatCount, m_iStep, and TWEEN_ASSERT.
Referenced by Update().
{
        if(!_bIsIterationStep()  && m_iRepeatCount >= 0 && m_iStep < 0 && m_fCurrentTime + m_fDt >= 0)
        {
                TWEEN_ASSERT(m_iStep == -1, "Step (%d) is too low, should be -1", m_iStep);
                m_Flags.ChangeMask(eIsIterationStep, true);
                m_iStep = 0;
                float fDt = 0.0f - m_fCurrentTime;
                m_fDt -= fDt;
                m_fCurrentTime = 0.0f;
                _CallCallback(ITweenListener::eBegin);
                _CallCallback(ITweenListener::eStart);
                _InnerUpdate(m_iStep, m_iStep - 1, _bIsIterationStep(), fDt);
        }
        else  if(!_bIsIterationStep() && m_iRepeatCount >= 0 && m_iStep > m_iRepeatCount * 2 && m_fCurrentTime + m_fDt <= 0.0f)
        {
                TWEEN_ASSERT(m_iStep != m_iRepeatCount*2 + 1, "Step (%d) is too big, should be %d", m_iStep, m_iRepeatCount*2 + 1);
                m_Flags.ChangeMask(eIsIterationStep, true);
                m_iStep = m_iRepeatCount *2 ;
                float fDt = 0.0f - m_fCurrentTime;
                m_fDt -= fDt;
                m_fCurrentTime = m_fDuration;
                _CallCallback(ITweenListener::eBackBegin);
                _CallCallback(ITweenListener::eBackStart);
                _InnerUpdate(m_iStep, m_iStep + 1, _bIsIterationStep(), fDt);
        }
}
void Tween::BaseTween::_UpdateStep () private
Definition at line 215 of file BaseTween.cpp.
References _bIsIterationStep(), _bIsReverse(), _bIsValid(), _CallCallback(), _ForceEndValues(), _ForceStartValues(), _InnerUpdate(), Tween::BitField< _Mask >::ChangeMask(), Tween::ITweenListener::eBackComplete, Tween::ITweenListener::eBackEnd, Tween::ITweenListener::eBackStart, Tween::ITweenListener::eComplete, Tween::ITweenListener::eEnd, eIsIterationStep, Tween::ITweenListener::eStart, m_fCurrentTime, m_fDt, m_fDuration, m_Flags, m_fRepeatDelay, m_iRepeatCount, and m_iStep.
Referenced by Update().
{
        while(_bIsValid(m_iStep))
        {
                if(!_bIsIterationStep() && m_fCurrentTime + m_fDt <= 0.0f)
                {
                        m_Flags.ChangeMask(eIsIterationStep, true);
                        -- m_iStep;
                        float fDt = 0.0f - m_fCurrentTime;
                        m_fDt -= fDt;
                        m_fCurrentTime = m_fDuration;
                        (_bIsReverse(m_iStep)) ? _ForceStartValues() : _ForceEndValues();
                        _CallCallback(ITweenListener::eBackStart);
                        _InnerUpdate(m_iStep, m_iStep + 1, _bIsIterationStep(), fDt);
                }
                else if(!_bIsIterationStep() && m_fCurrentTime + m_fDt >= m_fRepeatDelay)
                {
                        m_Flags.ChangeMask(eIsIterationStep, true);
                        ++ m_iStep;
                        float fDt = m_fRepeatDelay - m_fCurrentTime;
                        m_fDt -= fDt;
                        m_fCurrentTime = 0.0f;
                        (_bIsReverse(m_iStep)) ? _ForceEndValues() : _ForceStartValues();
                        _CallCallback(ITweenListener::eStart);
                        _InnerUpdate(m_iStep, m_iStep - 1, _bIsIterationStep(), fDt);
                }
                else if(_bIsIterationStep() && m_fCurrentTime + m_fDt < 0.0f)
                {
                        m_Flags.ChangeMask(eIsIterationStep, false);
                        -- m_iStep;
                        float fDt = 0.0f - m_fCurrentTime;
                        m_fDt -= fDt;
                        m_fCurrentTime = 0.0f;
                        _InnerUpdate(m_iStep, m_iStep + 1, _bIsIterationStep(), fDt);
                        _CallCallback(ITweenListener::eBackEnd);
                        if(m_iStep < 0 && m_iRepeatCount >= 0)
                                _CallCallback(ITweenListener::eBackComplete);
                        else
                                m_fCurrentTime = m_fRepeatDelay;
                }
                else if(_bIsIterationStep() && m_fCurrentTime + m_fDt  > m_fDuration)
                {
                        m_Flags.ChangeMask(eIsIterationStep, false);
                        ++ m_iStep;
                        float fDt = m_fDuration - m_fCurrentTime;
                        m_fDt -= fDt;
                        m_fCurrentTime = m_fDuration;
                        _InnerUpdate(m_iStep, m_iStep - 1, _bIsIterationStep(), fDt);
                        _CallCallback(ITweenListener::eEnd);
                        if(m_iStep > m_iRepeatCount*2 && m_iRepeatCount >= 0)
                                _CallCallback(ITweenListener::eComplete);
                        m_fCurrentTime = 0.0f;
                }
                else if(_bIsIterationStep())
                {
                        float fDt = m_fDt;
                        m_fDt -= fDt;
                        m_fCurrentTime += fDt;
                        _InnerUpdate(m_iStep, m_iStep, _bIsIterationStep(), fDt);
                        break;
                }
                else
                {
                        float fDt = m_fDt;
                        m_fDt -= fDt;
                        m_fCurrentTime += fDt;
                        break;
                }
        }
}
bool Tween::BaseTween::bIsFinished () const inline
Definition at line 35 of file BaseTween.h.
References Tween::BitField< _Mask >::bTestMask(), eIsFinished, eIsKilled, and m_Flags.
Referenced by Tween::TweenGroup::Update().
{ return m_Flags.bTestMask(eIsFinished) || m_Flags.bTestMask(eIsKilled); }
bool Tween::BaseTween::bIsInit () const inline
Definition at line 34 of file BaseTween.h.
References Tween::BitField< _Mask >::bTestMask(), eIsInit, and m_Flags.
Referenced by Tween::Tween::Target(), and Update().
{ return m_Flags.bTestMask(eIsInit);                    }
bool Tween::BaseTween::bIsPaused () const inline
Definition at line 37 of file BaseTween.h.
References Tween::BitField< _Mask >::bTestMask(), eIsPaused, and m_Flags.
Referenced by Update().
{ return m_Flags.bTestMask(eIsPaused);          }
bool Tween::BaseTween::bIsStarted () const inline
Definition at line 33 of file BaseTween.h.
References Tween::BitField< _Mask >::bTestMask(), eIsStarted, and m_Flags.
Referenced by _Repeat(), and Update().
{ return m_Flags.bTestMask(eIsStarted);         }
bool Tween::BaseTween::bIsYoyo () const inline
Definition at line 36 of file BaseTween.h.
References Tween::BitField< _Mask >::bTestMask(), eIsYoyo, and m_Flags.
Referenced by _bIsReverse().
{ return m_Flags.bTestMask(eIsYoyo);                    }
float Tween::BaseTween::fGetCurrentTime () const inline
Definition at line 31 of file BaseTween.h.
References m_fCurrentTime.
Referenced by Tween::Tween::_InnerUpdate().
{ return m_fCurrentTime;        }
float Tween::BaseTween::fGetDelay () const inline
Definition at line 27 of file BaseTween.h.
References m_fDelay.
{ return m_fDelay;              }
float Tween::BaseTween::fGetDuration () const inline
Definition at line 28 of file BaseTween.h.
References m_fDuration.
{ return m_fDuration;           }
float Tween::BaseTween::fGetFullDuration () const inline
Definition at line 29 of file BaseTween.h.
References m_fDelay, m_fDuration, m_fRepeatDelay, and m_iRepeatCount.
Referenced by Tween::Timeline::_Build(), and _ForceToEnd().
{ return (m_iRepeatCount == 0) ? m_fDelay + m_fDuration : (m_iRepeatCount < 0) ? -1.0f : m_fDelay + m_fDuration + (m_fRepeatDelay + m_fDuration) *m_iRepeatCount; }
float Tween::BaseTween::fGetRepeatDelay () const inline
Definition at line 30 of file BaseTween.h.
References m_fRepeatDelay.
{ return m_fRepeatDelay;        }
virtual void Tween::BaseTween::Free () inline virtual
Reimplemented in Tween::Tween, and Tween::Timeline.
Definition at line 49 of file BaseTween.h.
Referenced by Tween::Timeline::Free().
{}
int Tween::BaseTween::iGetRepeatCount () const inline
Definition at line 32 of file BaseTween.h.
References m_iRepeatCount.
Referenced by Tween::Timeline::_Build().
{ return m_iRepeatCount;        }
void Tween::BaseTween::Kill () inline
Definition at line 43 of file BaseTween.h.
References Tween::BitField< _Mask >::AddMask(), eIsKilled, and m_Flags.
Referenced by _KillTarget().
{ m_Flags.AddMask(eIsKilled); }
void Tween::BaseTween::Pause () inline
Definition at line 44 of file BaseTween.h.
References Tween::BitField< _Mask >::AddMask(), eIsPaused, and m_Flags.
{ m_Flags.AddMask(eIsPaused); }
void Tween::BaseTween::Resume () inline
Definition at line 45 of file BaseTween.h.
References eIsPaused, m_Flags, and Tween::BitField< _Mask >::SubMask().
{ m_Flags.SubMask(eIsPaused); }
void Tween::BaseTween::Update (float _fDt)
Definition at line 28 of file BaseTween.cpp.
References _bIsKilled(), _Initialize(), _UpdateCompletion(), _UpdateRelaunch(), _UpdateStep(), bIsInit(), bIsPaused(), bIsStarted(), m_fCurrentTime, and m_fDt.
Referenced by Tween::Timeline::_UpdateChildren().
{
        if(!bIsStarted() || bIsPaused() || _bIsKilled())
                return;
        m_fDt = _fDt;
        if(!bIsInit())
                _Initialize();
        if(bIsInit())
        {
                _UpdateRelaunch();
                _UpdateStep();
                _UpdateCompletion();
        }
        m_fCurrentTime += m_fDt;
        m_fDt = 0.0f;
}
Friends And Related Function Documentation
friend class Manager friend
Definition at line 21 of file BaseTween.h.
friend class Timeline friend
Definition at line 22 of file BaseTween.h.
friend class TweenGroup friend
Definition at line 20 of file BaseTween.h.
Member Data Documentation
float Tween::BaseTween::m_fCurrentTime private
Definition at line 108 of file BaseTween.h.
Referenced by _ForceToEnd(), _ForceToStart(), _Initialize(), _Reset(), _Start(), _UpdateRelaunch(), _UpdateStep(), fGetCurrentTime(), and Update().
float Tween::BaseTween::m_fDelay protected
Definition at line 104 of file BaseTween.h.
Referenced by _Delay(), _ForceToStart(), _Initialize(), _Reset(), fGetDelay(), and fGetFullDuration().
float Tween::BaseTween::m_fDt private
Definition at line 109 of file BaseTween.h.
Referenced by _Initialize(), _Reset(), _UpdateRelaunch(), _UpdateStep(), and Update().
float Tween::BaseTween::m_fDuration protected
Definition at line 105 of file BaseTween.h.
Referenced by Tween::Timeline::_Build(), Tween::Timeline::_ForceEndValues(), Tween::Tween::_InnerUpdate(), _Reset(), _UpdateRelaunch(), _UpdateStep(), fGetDuration(), fGetFullDuration(), and Tween::Tween::Setup().
BitField<uint8> Tween::BaseTween::m_Flags private
Definition at line 121 of file BaseTween.h.
Referenced by _bIsIterationStep(), _bIsKilled(), _ForceToEnd(), _ForceToStart(), _Initialize(), _Repeat(), _Reset(), _Start(), _UpdateCompletion(), _UpdateRelaunch(), _UpdateStep(), bIsFinished(), bIsInit(), bIsPaused(), bIsStarted(), bIsYoyo(), Kill(), Pause(), and Resume().
float Tween::BaseTween::m_fRepeatDelay private
Definition at line 107 of file BaseTween.h.
Referenced by _Repeat(), _Reset(), _UpdateStep(), fGetFullDuration(), and fGetRepeatDelay().
int Tween::BaseTween::m_iListenerID private
Definition at line 99 of file BaseTween.h.
Referenced by _CallCallback(), and _SetListener().
int Tween::BaseTween::m_iListenerTriggers private
Definition at line 98 of file BaseTween.h.
Referenced by _CallCallback(), and _SetListener().
int Tween::BaseTween::m_iRepeatCount private
Definition at line 101 of file BaseTween.h.
Referenced by _bIsValid(), _ForceToEnd(), _Repeat(), _Reset(), _UpdateCompletion(), _UpdateRelaunch(), _UpdateStep(), fGetFullDuration(), and iGetRepeatCount().
int Tween::BaseTween::m_iStep private
Definition at line 100 of file BaseTween.h.
Referenced by _ForceToEnd(), _ForceToStart(), _Initialize(), _Reset(), _UpdateCompletion(), _UpdateRelaunch(), and _UpdateStep().
ITweenListener* Tween::BaseTween::m_pListener private
Definition at line 97 of file BaseTween.h.
Referenced by _CallCallback(), and _SetListener().
The documentation for this class was generated from the following files:
SRC/Tween/BaseTween.h
SRC/Tween/BaseTween.cpp