TweenEngineLib: Tween::Timeline Class Reference
Tween::Timeline Class Reference
#include <Timeline.h>
Public Types
enum ETimelineMode { eSequence, eParallel }
Public Member Functions
Timeline ()
virtual ~Timeline ()
Timeline * Push (Tween *_pTween)
Timeline * Push (Timeline *_pTimeline)
Timeline * PushPause (float _fTime)
Timeline * BeginSequence ()
Timeline * BeginParallel ()
Timeline * End ()
Timeline * Setup (ETimelineMode _eMode)
virtual void Free ()
Public Member Functions inherited from Tween::TemplatedTween< Timeline >
TemplatedTween ()
virtual ~TemplatedTween ()
Timeline * Build ()
Timeline * Start ()
Timeline * Start (Manager *_pManager)
Timeline * Start (Manager *_pManager, uint8 _GroupID)
Timeline * Delay (float _fDelay)
Timeline * Repeat (int _Count, float _fDelay, bool _bYoyo=false)
Timeline * SetListener (ITweenListener *_pListener, int _iID=-1, int _iTriggers=ITweenListener::eComplete)
Public Member Functions inherited from Tween::BaseTween
BaseTween ()
virtual ~BaseTween ()
float fGetDelay () const
float fGetDuration () const
float fGetFullDuration () const
float fGetRepeatDelay () const
float fGetCurrentTime () const
int iGetRepeatCount () const
bool bIsStarted () const
bool bIsInit () const
bool bIsFinished () const
bool bIsYoyo () const
bool bIsPaused () const
void Kill ()
void Pause ()
void Resume ()
void Update (float _fDt)
Static Public Member Functions
static Timeline * CreateSequence ()
static Timeline * CreateParallel ()
Protected Member Functions
virtual void _Reset ()
virtual void _Build ()
virtual void _Start ()
virtual void _InnerUpdate (int _iStep, int _iLastStep, bool _bIsIterationStep, float _fDt)
virtual void _ForceStartValues ()
virtual void _ForceEndValues ()
virtual bool _bContainsTarget (ITweenable *_pTarget) const
virtual bool _bContainsTarget (ITweenable *_pTarget, int _iType) const
Static Protected Attributes
static Pool< Timeline > s_Pool = Pool<Timeline>()
Private Member Functions
void _UpdateChildren (float _fDt, bool _bBackward=false)
Private Attributes
std::vector< BaseTween * > m_Children
Timeline * m_pCurrent
Timeline * m_pParent
ETimelineMode m_eMode
bool m_bIsBuilt
Friends
class Pool< Timeline >
Additional Inherited Members
Protected Attributes inherited from Tween::BaseTween
float m_fDelay
float m_fDuration
Detailed Description
Definition at line 18 of file Timeline.h.
Member Enumeration Documentation
enum Tween::Timeline::ETimelineMode
Enumerator:
eSequence
eParallel
Definition at line 30 of file Timeline.h.
        {
                eSequence,
                eParallel,
        };
Constructor & Destructor Documentation
Tween::Timeline::Timeline ()
Definition at line 45 of file Timeline.cpp.
: TemplatedTween<Timeline>()
, m_pCurrent(NULL)
, m_pParent(NULL)
, m_eMode(eSequence)
, m_bIsBuilt(false)
{
}
Tween::Timeline::~Timeline () virtual
Definition at line 55 of file Timeline.cpp.
{
}
Member Function Documentation
bool Tween::Timeline::_bContainsTarget (ITweenable * _pTarget) const protected virtual
Implements Tween::BaseTween.
Definition at line 341 of file Timeline.cpp.
References Tween::BaseTween::_bContainsTarget(), and m_Children.
{
        size_t iSize = m_Children.size();
        for (size_t i = 0; i < iSize; ++i)
        {
                BaseTween* pTween = m_Children[i];
                if(pTween->_bContainsTarget(_pTarget))
                        return true;
        }
        return false;
}
bool Tween::Timeline::_bContainsTarget (ITweenable * _pTarget, int _iType) const protected virtual
Implements Tween::BaseTween.
Definition at line 354 of file Timeline.cpp.
References Tween::BaseTween::_bContainsTarget(), and m_Children.
{
        size_t iSize = m_Children.size();
        for (size_t i = 0; i < iSize; ++i)
        {
                BaseTween* pTween = m_Children[i];
                if(pTween->_bContainsTarget(_pTarget, _iType))
                        return true;
        }
        return false;
}
void Tween::Timeline::_Build () protected virtual
Reimplemented from Tween::BaseTween.
Definition at line 73 of file Timeline.cpp.
References Tween::BaseTween::_Build(), Tween::BaseTween::_Delay(), eParallel, eSequence, Tween::BaseTween::fGetFullDuration(), Tween::BaseTween::iGetRepeatCount(), m_bIsBuilt, m_Children, m_eMode, Tween::BaseTween::m_fDuration, and TWEEN_ASSERT.
{
        if (m_bIsBuilt)
                return;
        m_fDuration = 0.0f;
        for (size_t i=0; i<m_Children.size(); i++)
        {
                BaseTween* pTween = m_Children[i];
                if (pTween->iGetRepeatCount() < 0)
                {
                        TWEEN_ASSERT(pTween->iGetRepeatCount() < 0, "You can't push an object with infinite repetitions in a timeline");
                        return;
                }
                pTween->_Build();
                float fTweenFullDUration = pTween->fGetFullDuration();
                switch (m_eMode) {
                case eSequence:
{
                                float fDelay = m_fDuration;
                                m_fDuration += fTweenFullDUration;
                                pTween->_Delay(fDelay);
                        }
                        break;
                case eParallel:
                        m_fDuration = (m_fDuration > fTweenFullDUration)? m_fDuration : fTweenFullDUration;
                        break;
                }
        }
        m_bIsBuilt = true;
        return;
}
void Tween::Timeline::_ForceEndValues () protected virtual
Implements Tween::BaseTween.
Definition at line 330 of file Timeline.cpp.
References Tween::BaseTween::_ForceToEnd(), m_Children, and Tween::BaseTween::m_fDuration.
Referenced by _InnerUpdate().
{
        size_t iSize = m_Children.size();
        for (size_t i = 0; i < iSize; ++i)
        {
                BaseTween* pTween = m_Children[i];
                pTween->_ForceToEnd(m_fDuration);
        }
}
void Tween::Timeline::_ForceStartValues () protected virtual
Implements Tween::BaseTween.
Definition at line 315 of file Timeline.cpp.
References Tween::BaseTween::_ForceToStart(), and m_Children.
Referenced by _InnerUpdate().
{
        size_t iSize = m_Children.size();
        for (size_t i = iSize-1 ; i >= 0 ; --i)
        {
                BaseTween* pTween = m_Children[i];
                pTween->_ForceToStart();
                // We beak if i == 0 as i is unsigned, if we -- it it will be positive again
                if(i == 0)
                        break;
        }
}
void Tween::Timeline::_InnerUpdate (int _iStep, int _iLastStep, bool _bIsIterationStep, float _fDt) protected virtual
Reimplemented from Tween::BaseTween.
Definition at line 264 of file Timeline.cpp.
References Tween::BaseTween::_bIsReverse(), _ForceEndValues(), _ForceStartValues(), _UpdateChildren(), and TWEEN_ASSERT.
{
        if(!_bIsIterationStep && _iStep > _iLastStep)
        {
                TWEEN_ASSERT(_fDt >= 0, "Delta should be positive");
                float fNewDelta = _bIsReverse(_iLastStep) ? (-_fDt - 1.0f) : (_fDt + 1.0f);
                _UpdateChildren(fNewDelta);
                return;
        }
        if(!_bIsIterationStep && _iStep < _iLastStep)
        {
                TWEEN_ASSERT(_fDt <= 0, "Delta should be positive");
                float fNewDelta = _bIsReverse(_iLastStep) ? (-_fDt - 1.0f) : (_fDt + 1.0f);
                _UpdateChildren(fNewDelta, true);
                return;
        }
        TWEEN_ASSERT(_bIsIterationStep, "Not an iteration step and last step equal to step should not happen");
        if(_iStep > _iLastStep)
        {
                if(_bIsReverse(_iStep))
                        _ForceEndValues();
                else
                        _ForceStartValues();
                _UpdateChildren(_fDt);
        }
        else if( _iStep < _iLastStep)
        {
                if(_bIsReverse(_iStep))
                        _ForceStartValues();
                else
                        _ForceEndValues();
                _UpdateChildren(_fDt, true);
        }
        else
        {
                float fDt = _bIsReverse(_iStep) ? -_fDt : _fDt;
                if(_fDt >= 0.0f)
                        _UpdateChildren(fDt);
                else
                        _UpdateChildren(fDt, true);
        }
}
void Tween::Timeline::_Reset () protected virtual
Reimplemented from Tween::BaseTween.
Definition at line 61 of file Timeline.cpp.
References Tween::BaseTween::_Reset(), eSequence, m_bIsBuilt, m_Children, m_eMode, m_pCurrent, and m_pParent.
{
        TemplatedTween<Timeline>::_Reset();
        m_Children.clear();
        m_pCurrent = NULL;
        m_pParent = NULL;
        m_bIsBuilt = false;
        m_eMode = eSequence;
}
void Tween::Timeline::_Start () protected virtual
Reimplemented from Tween::BaseTween.
Definition at line 216 of file Timeline.cpp.
References Tween::BaseTween::_Start(), and m_Children.
{
        TemplatedTween<Timeline>::_Start();
        for (size_t i=0; i<m_Children.size(); i++)
        {
                BaseTween* pTween = m_Children[i];
                pTween->_Start();
        }
}
void Tween::Timeline::_UpdateChildren (float _fDt, bool _bBackward = false) private
Definition at line 240 of file Timeline.cpp.
References m_Children, and Tween::BaseTween::Update().
Referenced by _InnerUpdate().
{
        size_t iSize = m_Children.size();
        if(!_bBackward)
        {
                for (size_t i = 0; i < iSize; ++i)
                {
                        BaseTween* pTween = m_Children[i];
                        pTween->Update(_fDt);
                }
        }
        else
        {
                for (size_t i = iSize-1 ; i >= 0 ; --i)
                {
                        BaseTween* pTween = m_Children[i];
                        pTween->Update(_fDt);
                        if(i == 0)                      // We break if i == 0 because as i is unsigned, if we -- it, it will be positive again and the loop become infinite
                                break;
                }
        }
}
Timeline * Tween::Timeline::BeginParallel ()
Definition at line 184 of file Timeline.cpp.
References eParallel, Tween::Pool< T >::Get(), m_bIsBuilt, m_Children, m_eMode, m_pCurrent, m_pParent, s_Pool, and TWEEN_ASSERT.
{
        TWEEN_ASSERT(!m_bIsBuilt, "You can't push anything to a timeline once it is started/built");
        TWEEN_ASSERT(m_pCurrent, "Timeline doesn't have a current timeline");
        if(!m_bIsBuilt && m_pCurrent)
        {
                Timeline* timeline = s_Pool.Get();
                timeline->m_pParent = m_pCurrent;
                timeline->m_eMode = eParallel;
                m_pCurrent->m_Children.push_back(timeline);
                m_pCurrent = timeline;
        }
        return this;
}
Timeline * Tween::Timeline::BeginSequence ()
Definition at line 167 of file Timeline.cpp.
References eSequence, Tween::Pool< T >::Get(), m_bIsBuilt, m_Children, m_eMode, m_pCurrent, m_pParent, s_Pool, and TWEEN_ASSERT.
{
        TWEEN_ASSERT(!m_bIsBuilt, "You can't push anything to a timeline once it is started/built");
        TWEEN_ASSERT(m_pCurrent, "Timeline doesn't have a current timeline");
        if(!m_bIsBuilt && m_pCurrent)
        {
                Timeline* timeline = s_Pool.Get();
                timeline->m_pParent = m_pCurrent;
                timeline->m_eMode = eSequence;
                m_pCurrent->m_Children.push_back(timeline);
                m_pCurrent = timeline;
        }
        return this;
}
Timeline * Tween::Timeline::CreateParallel () static
Definition at line 37 of file Timeline.cpp.
References Setup().
{
        Timeline* timeline = s_Pool.Get();
        timeline->Setup(eParallel);
        return timeline;
}
Timeline * Tween::Timeline::CreateSequence () static
Definition at line 29 of file Timeline.cpp.
References Setup().
{
        Timeline* timeline = s_Pool.Get();
        timeline->Setup(eSequence);
        return timeline;
}
Timeline * Tween::Timeline::End ()
Definition at line 201 of file Timeline.cpp.
References m_bIsBuilt, m_pCurrent, m_pParent, and TWEEN_ASSERT.
{
        TWEEN_ASSERT(!m_bIsBuilt, "You can't push anything to a timeline once it is started/built");
        TWEEN_ASSERT(m_pCurrent, "Timeline doesn't have a current timeline");
        TWEEN_ASSERT(m_pCurrent != this, "Too many call to End");
        if(!m_bIsBuilt && m_pCurrent && m_pCurrent != this)
        {
                m_pCurrent = m_pCurrent->m_pParent;
        }
        return this;
}
void Tween::Timeline::Free () virtual
Reimplemented from Tween::BaseTween.
Definition at line 228 of file Timeline.cpp.
References Tween::BaseTween::Free(), Tween::Pool< T >::Free(), m_Children, and s_Pool.
{
        for (size_t i=0; i<m_Children.size(); i++)
        {
                BaseTween* pTween = m_Children[i];
                pTween->Free();
        }
        s_Pool.Free(this);
}
Timeline * Tween::Timeline::Push (Tween * _pTween)
Definition at line 122 of file Timeline.cpp.
References m_bIsBuilt, m_Children, m_pCurrent, and TWEEN_ASSERT.
{
        TWEEN_ASSERT(_pTween, "Trying to push a null timeline");
        TWEEN_ASSERT(!m_bIsBuilt, "You can't push anything to a timeline once it is started/built");
        TWEEN_ASSERT(m_pCurrent, "Timeline doesn't have a current timeline, push failed");
        if(!m_bIsBuilt && m_pCurrent && _pTween)
        {
                m_pCurrent->m_Children.push_back(_pTween);
        }
        return this;
}
Timeline * Tween::Timeline::Push (Timeline * _pTimeline)
Definition at line 137 of file Timeline.cpp.
References m_bIsBuilt, m_Children, m_pCurrent, m_pParent, and TWEEN_ASSERT.
{
        TWEEN_ASSERT(!m_bIsBuilt, "You can't push anything to a timeline once it is started/built");
        TWEEN_ASSERT(m_pCurrent, "Timeline doesn't have a current timeline, push failed");
        TWEEN_ASSERT(_pTimeline, "Trying to push a null timeline");
        if(!m_bIsBuilt && _pTimeline && m_pCurrent)
        {
                TWEEN_ASSERT(_pTimeline->m_pCurrent == _pTimeline, "Begin()/End() count is not correct");
                _pTimeline->m_pParent = m_pCurrent;
                m_pCurrent->m_Children.push_back(_pTimeline);
        }
        return this;
}
Timeline * Tween::Timeline::PushPause (float _fTime)
Definition at line 155 of file Timeline.cpp.
References Tween::TemplatedTween< Timeline >::Delay(), m_bIsBuilt, m_Children, m_pCurrent, Tween::Tween::Mark(), and TWEEN_ASSERT.
{
        TWEEN_ASSERT(!m_bIsBuilt, "You can't push anything to a timeline once it is started/built");
        TWEEN_ASSERT(m_pCurrent, "Timeline doesn't have a current timeline, pushPause failed");
        if(m_pCurrent && !m_bIsBuilt)
        {
                m_pCurrent->m_Children.push_back(Tween::Mark()->Delay(_fTime));
        }
        return this;
}
Timeline * Tween::Timeline::Setup (ETimelineMode _eMode)
Definition at line 114 of file Timeline.cpp.
References m_eMode, and m_pCurrent.
Referenced by CreateParallel(), and CreateSequence().
{
        m_eMode = _eMode;
        m_pCurrent = this;
        return this;
}
Friends And Related Function Documentation
friend class Pool< Timeline > friend
Definition at line 21 of file Timeline.h.
Member Data Documentation
bool Tween::Timeline::m_bIsBuilt private
Definition at line 72 of file Timeline.h.
Referenced by _Build(), _Reset(), BeginParallel(), BeginSequence(), End(), Push(), and PushPause().
std::vector< BaseTween* > Tween::Timeline::m_Children private
Definition at line 68 of file Timeline.h.
Referenced by _bContainsTarget(), _Build(), _ForceEndValues(), _ForceStartValues(), _Reset(), _Start(), _UpdateChildren(), BeginParallel(), BeginSequence(), Free(), Push(), and PushPause().
ETimelineMode Tween::Timeline::m_eMode private
Definition at line 71 of file Timeline.h.
Referenced by _Build(), _Reset(), BeginParallel(), BeginSequence(), and Setup().
Timeline* Tween::Timeline::m_pCurrent private
Definition at line 69 of file Timeline.h.
Referenced by _Reset(), BeginParallel(), BeginSequence(), End(), Push(), PushPause(), and Setup().
Timeline* Tween::Timeline::m_pParent private
Definition at line 70 of file Timeline.h.
Referenced by _Reset(), BeginParallel(), BeginSequence(), End(), and Push().
Pool< Timeline > Tween::Timeline::s_Pool = Pool<Timeline>() static protected
Definition at line 27 of file Timeline.h.
Referenced by BeginParallel(), BeginSequence(), and Free().
The documentation for this class was generated from the following files:
SRC/Tween/Timeline.h
SRC/Tween/Timeline.cpp