TweenEngineLib: Tween::Tween Class Reference
Tween::Tween Class Reference
#include <Tween.h>
Public Member Functions
Tween ()
virtual ~Tween ()
int GetType () const
ITweenable * GetTweenable () const
Easing::Easing * GetEasing () const
Tween * Ease (Easing::Easing *_pEquation)
Tween * SetPath (Path::Path *_pPath)
Tween * Target (float _fTarget1, bool _bRelative=false)
Tween * Target (float _fTarget1, float _fTarget2, bool _bRelative=false)
Tween * Target (float _fTarget1, float _fTarget2, float _fTarget3, bool _bRelative=false)
Tween * Target (const float *_fTargets, int _iTargetCount, bool _bRelative=false)
Tween * Waypoint (float _fTarget1)
Tween * Waypoint (float _fTarget1, float _fTarget2)
Tween * Waypoint (float _fTarget1, float _fTarget2, float _fTarget3)
Tween * Waypoint (const float *_fTargets, int _iTargetCount)
Tween * SetIsFrom (bool _bIsFrom)
Tween * Setup (ITweenable *_pTarget, int _iType, float _fDuration)
virtual void Free ()
Public Member Functions inherited from Tween::TemplatedTween< Tween >
TemplatedTween ()
virtual ~TemplatedTween ()
Tween * Build ()
Tween * Start ()
Tween * Start (Manager *_pManager)
Tween * Start (Manager *_pManager, uint8 _GroupID)
Tween * Delay (float _fDelay)
Tween * Repeat (int _Count, float _fDelay, bool _bYoyo=false)
Tween * SetListener (ITweenListener *_pListener, int _iID=-1, int _iTriggers=ITweenListener::eComplete)
Public Member Functions inherited from Tween::BaseTween
BaseTween ()
virtual ~BaseTween ()
float fGetDelay () const
float fGetDuration () const
float fGetFullDuration () const
float fGetRepeatDelay () const
float fGetCurrentTime () const
int iGetRepeatCount () const
bool bIsStarted () const
bool bIsInit () const
bool bIsFinished () const
bool bIsYoyo () const
bool bIsPaused () const
void Kill ()
void Pause ()
void Resume ()
void Update (float _fDt)
Static Public Member Functions
static void SetAttributesLimit (uint8 _Limit)
static void SetWaypointsLimit (uint8 _Limit)
static void SetDefaultEquation (Easing::Easing *_pDefaultEquation)
static Tween * To (ITweenable *_pTarget, int _iType, float _fDuration)
static Tween * From (ITweenable *_pTarget, int _iType, float _fDuration)
static Tween * Set (ITweenable *_pTarget, int _iType)
static Tween * Call (ITweenListener *_pCallBack)
static Tween * Mark ()
Protected Member Functions
virtual void _Reset ()
virtual void _Build ()
virtual void _InnerInitialize ()
virtual void _InnerUpdate (int _iStep, int _iLastStep, bool _bIsIterationStep, float _fDt)
virtual void _ForceStartValues ()
virtual void _ForceEndValues ()
virtual bool _bContainsTarget (ITweenable *_pTarget) const
virtual bool _bContainsTarget (ITweenable *_pTarget, int _iType) const
Static Protected Attributes
static const int INVALID_TYPE = -1
static uint8 s_AttributesLimit = 4
static uint8 s_WaypointsLimit = 0
static Pool< Tween > s_Pool = Pool<Tween>()
static Easing::Easing * s_pDefaultEquation = &(Easing::QUAD_INOUT)
Private Attributes
int m_iType
ITweenable * m_pTarget
Easing::Easing * m_pEquation
Path::Path * m_pPath
std::vector< float > m_fStartValues
std::vector< float > m_fTargetValues
std::vector< float > m_fWaypoints
std::vector< float > m_fAttributesBuffer
std::vector< float > m_fWaypointsBuffer
uint8 m_ucAttributesLimit
uint8 m_ucWaypointsLimit
uint8 m_ucCombinedAttributesCount
uint8 m_ucWaypointsCount
bool m_bIsFrom
bool m_bIsRelative
Friends
class Pool< Tween >
Additional Inherited Members
Protected Attributes inherited from Tween::BaseTween
float m_fDelay
float m_fDuration
Detailed Description
Definition at line 29 of file Tween.h.
Constructor & Destructor Documentation
Tween::Tween::Tween ()
Definition at line 37 of file Tween.cpp.
: TemplatedTween<Tween>()
, m_iType(INVALID_TYPE)
, m_pEquation(NULL)
, m_pPath(NULL)
, m_bIsFrom(false)
, m_bIsRelative(false)
, m_ucCombinedAttributesCount(0)
, m_ucWaypointsCount(0)
, m_pTarget(NULL)
, m_ucAttributesLimit(s_AttributesLimit)
, m_ucWaypointsLimit(s_WaypointsLimit)
{
}
Tween::Tween::~Tween () virtual
Definition at line 54 of file Tween.cpp.
{
}
Member Function Documentation
bool Tween::Tween::_bContainsTarget (ITweenable * _pTarget) const protected virtual
Implements Tween::BaseTween.
Definition at line 375 of file Tween.cpp.
References m_pTarget.
{
        return m_pTarget == _pTarget;
}
bool Tween::Tween::_bContainsTarget (ITweenable * _pTarget, int _iType) const protected virtual
Implements Tween::BaseTween.
Definition at line 381 of file Tween.cpp.
References m_iType, and m_pTarget.
{
        return _pTarget == m_pTarget && m_iType == _iType;
}
void Tween::Tween::_Build () protected virtual
Reimplemented from Tween::BaseTween.
Definition at line 255 of file Tween.cpp.
{
}
void Tween::Tween::_ForceEndValues () protected virtual
Implements Tween::BaseTween.
Definition at line 368 of file Tween.cpp.
References Tween::ITweenable::_SetValues(), m_fTargetValues, m_iType, m_pTarget, and m_ucCombinedAttributesCount.
{
        if(m_pTarget)
                m_pTarget->_SetValues(m_iType,&(m_fTargetValues[0]), m_ucCombinedAttributesCount);
}
void Tween::Tween::_ForceStartValues () protected virtual
Implements Tween::BaseTween.
Definition at line 361 of file Tween.cpp.
References Tween::ITweenable::_SetValues(), m_fStartValues, m_iType, m_pTarget, and m_ucCombinedAttributesCount.
{
        if(m_pTarget)
                m_pTarget->_SetValues(m_iType,&(m_fStartValues[0]), m_ucCombinedAttributesCount);
}
void Tween::Tween::_InnerInitialize () protected virtual
Reimplemented from Tween::BaseTween.
Definition at line 260 of file Tween.cpp.
References Tween::ITweenable::_GetValues(), m_bIsFrom, m_bIsRelative, m_fAttributesBuffer, m_fStartValues, m_fTargetValues, m_fWaypoints, m_fWaypointsBuffer, m_iType, m_pTarget, m_ucCombinedAttributesCount, and m_ucWaypointsCount.
{
        if(!m_pTarget)
                return;
        m_fStartValues.assign(m_ucCombinedAttributesCount, 0.0f);
        m_fAttributesBuffer.assign(m_ucCombinedAttributesCount, 0.0f);
        m_fWaypointsBuffer.assign((2 + m_ucWaypointsCount) * m_ucCombinedAttributesCount, 0.0f);
        m_pTarget->_GetValues(m_iType, &m_fStartValues[0], m_ucCombinedAttributesCount);
        for(int i=0; i < m_ucCombinedAttributesCount; ++i)
        {
                m_fTargetValues[i] += m_bIsRelative ? m_fStartValues[i] : 0.0f;
                for (uint8 j=0; j < m_ucWaypointsCount; ++j)
                {
                        m_fWaypoints[j*m_ucCombinedAttributesCount+i] += m_bIsRelative ? m_fStartValues[i] : 0.0f;
                }
                if(m_bIsFrom)
                {
                        float fTmp = m_fStartValues[i];
                        m_fStartValues[i] = m_fTargetValues[i];
                        m_fTargetValues[i] = fTmp;
                }
        }
}
void Tween::Tween::_InnerUpdate (int _iStep, int _iLastStep, bool _bIsIterationStep, float _fDt) protected virtual
Reimplemented from Tween::BaseTween.
Definition at line 291 of file Tween.cpp.
References Tween::BaseTween::_bIsReverse(), Tween::ITweenable::_SetValues(), Tween::Path::Path::Compute(), Tween::Easing::Easing::Compute(), Tween::BaseTween::fGetCurrentTime(), m_fAttributesBuffer, Tween::BaseTween::m_fDuration, m_fStartValues, m_fTargetValues, m_fWaypoints, m_fWaypointsBuffer, m_iType, m_pEquation, m_pPath, m_pTarget, m_ucCombinedAttributesCount, m_ucWaypointsCount, and TWEEN_ASSERT.
{
        if(!m_pTarget || !m_pEquation)
        {
                TWEEN_ASSERT(m_pTarget, "No Tweenable assigned");
                TWEEN_ASSERT(m_pEquation, "No Equation assigned");
                return;
        }
        if(!_bIsIterationStep && _iStep > _iLastStep)
        {
                m_pTarget->_SetValues(m_iType, _bIsReverse(_iLastStep) ? &(m_fStartValues[0]) : &(m_fTargetValues[0]), m_ucCombinedAttributesCount );
                return;
        }
        if(!_bIsIterationStep && _iStep < _iLastStep)
        {
                m_pTarget->_SetValues(m_iType, _bIsReverse(_iLastStep) ? &(m_fTargetValues[0]) : &(m_fStartValues[0]), m_ucCombinedAttributesCount );
                return;
        }
        TWEEN_ASSERT(_bIsIterationStep, "");
        TWEEN_ASSERT(fGetCurrentTime() >= 0.0f, "");
        TWEEN_ASSERT(fGetCurrentTime() <= m_fDuration, "");
        const float eqZero = 0.00000000001f;
        if(m_fDuration < eqZero && _fDt > -eqZero)
        {
                m_pTarget->_SetValues(m_iType, _bIsReverse(_iStep) ? &(m_fTargetValues[0]) :  &(m_fStartValues[0]), m_ucCombinedAttributesCount);
                return;
        }
        if(m_fDuration < eqZero && _fDt < eqZero)
        {
                m_pTarget->_SetValues(m_iType, _bIsReverse(_iStep) ? &(m_fStartValues[0]) :  &(m_fTargetValues[0]), m_ucCombinedAttributesCount);
                return;
        }
        float fTime = _bIsReverse(_iStep)? m_fDuration - fGetCurrentTime() : fGetCurrentTime();
        float t = m_pEquation->Compute(fTime, m_fDuration);
        if(m_ucWaypointsCount == 0 || m_pPath == NULL)
        {
                for(int i = 0; i < m_ucCombinedAttributesCount; ++i)
                {
                        m_fAttributesBuffer[i] = m_fStartValues[i] + t * (m_fTargetValues[i] - m_fStartValues[i]);
                }
        }
        else
        {
                for (uint8 i = 0; i < m_ucCombinedAttributesCount; ++i)
                {
                        m_fWaypointsBuffer[0] = m_fStartValues[i];
                        m_fWaypointsBuffer[1 + m_ucWaypointsCount] = m_fTargetValues[i];
                        for (uint8 j = 0; j < m_ucWaypointsCount; ++j)
{
                                m_fWaypointsBuffer[j+1] = m_fWaypoints[j*m_ucCombinedAttributesCount+i];
                        }
                        m_fAttributesBuffer[i] = m_pPath->Compute(t, &(m_fWaypointsBuffer[0]), m_ucWaypointsCount+2);
                }
        }
        m_pTarget->_SetValues(m_iType,&(m_fAttributesBuffer[0]), m_ucCombinedAttributesCount);
}
void Tween::Tween::_Reset () protected virtual
Reimplemented from Tween::BaseTween.
Definition at line 59 of file Tween.cpp.
References Tween::BaseTween::_Reset(), INVALID_TYPE, m_bIsFrom, m_bIsRelative, m_fAttributesBuffer, m_fStartValues, m_fTargetValues, m_fWaypoints, m_fWaypointsBuffer, m_iType, m_pEquation, m_pPath, m_pTarget, m_ucCombinedAttributesCount, and m_ucWaypointsCount.
{
        TemplatedTween<Tween>::_Reset();
        m_iType = INVALID_TYPE;
        m_pEquation = NULL;
        m_pPath = NULL;
        m_pTarget = NULL;
        m_bIsFrom = false;
        m_bIsRelative = false;
        m_ucCombinedAttributesCount = 0;
        m_ucWaypointsCount = 0;
        m_fStartValues.clear();
        m_fTargetValues.clear();
        m_fWaypoints.clear();
        m_fAttributesBuffer.clear();
        m_fWaypointsBuffer.clear();
}
Tween * Tween::Tween::Call (ITweenListener * _pCallBack) static
Definition at line 127 of file Tween.cpp.
References Tween::ITweenListener::eStart, Tween::Pool< T >::Get(), INVALID_TYPE, and s_Pool.
{
        Tween* pTween = s_Pool.Get();
        if(pTween)
        {
                pTween->Setup(NULL, INVALID_TYPE, 0.0f)->SetListener(_pCallBack, -1, ITweenListener::eStart);
        }
        return pTween;
}
Tween * Tween::Tween::Ease (Easing::Easing * _pEquation)
Definition at line 156 of file Tween.cpp.
References m_pEquation, and TWEEN_ASSERT.
{
        TWEEN_ASSERT(_pEquation, "Equation is null");
        m_pEquation = _pEquation;
        return this;
}
void Tween::Tween::Free () virtual
Reimplemented from Tween::BaseTween.
Definition at line 249 of file Tween.cpp.
References Tween::Pool< T >::Free(), and s_Pool.
{
        s_Pool.Free(this);
}
Tween * Tween::Tween::From (ITweenable * _pTarget, int _iType, float _fDuration) static
Definition at line 107 of file Tween.cpp.
References To().
{
        Tween* pTween  = To(_pTarget, _iType , _fDuration );
        if(pTween)
                pTween->SetIsFrom(true);
        return pTween;
}
Easing::Easing* Tween::Tween::GetEasing () const inline
Definition at line 68 of file Tween.h.
References m_pEquation.
{ return m_pEquation; }
ITweenable* Tween::Tween::GetTweenable () const inline
Definition at line 67 of file Tween.h.
References m_pTarget.
{ return m_pTarget; }
int Tween::Tween::GetType () const inline
Definition at line 66 of file Tween.h.
References m_iType.
{ return m_iType; }
Tween * Tween::Tween::Mark () static
Definition at line 138 of file Tween.cpp.
References Tween::Pool< T >::Get(), INVALID_TYPE, and s_Pool.
Referenced by Tween::Timeline::PushPause().
{
        Tween* pTween = s_Pool.Get();
        if(pTween)
        {
                pTween->Setup(NULL, INVALID_TYPE, 0.0f);
        }
        return pTween;
}
Tween * Tween::Tween::Set (ITweenable * _pTarget, int _iType) static
Definition at line 116 of file Tween.cpp.
References Tween::Pool< T >::Get(), s_pDefaultEquation, and s_Pool.
{
        Tween* pTween = s_Pool.Get();
        if(pTween)
        {
                pTween->Setup(_pTarget, _iType, 0.0f)->Ease(s_pDefaultEquation);
        }
        return pTween;
}
static void Tween::Tween::SetAttributesLimit (uint8 _Limit) inline static
Definition at line 41 of file Tween.h.
References s_AttributesLimit.
        {
                s_AttributesLimit = _Limit;
        }
static void Tween::Tween::SetDefaultEquation (Easing::Easing * _pDefaultEquation) inline static
Definition at line 51 of file Tween.h.
References s_pDefaultEquation.
        {
                s_pDefaultEquation = _pDefaultEquation;
        }
Tween * Tween::Tween::SetIsFrom (bool _bIsFrom)
Definition at line 149 of file Tween.cpp.
References m_bIsFrom.
{
        m_bIsFrom = _bIsFrom;
        return this;
}
Tween * Tween::Tween::SetPath (Path::Path * _pPath)
Definition at line 164 of file Tween.cpp.
References m_pPath, and TWEEN_ASSERT.
{
        TWEEN_ASSERT(_pPath, "Path is null");
        m_pPath = _pPath;
        return this;
}
Tween * Tween::Tween::Setup (ITweenable * _pTarget, int _iType, float _fDuration)
Definition at line 81 of file Tween.cpp.
References Tween::ITweenable::_GetValuesCount(), Tween::BaseTween::m_fDuration, m_iType, m_pTarget, and m_ucCombinedAttributesCount.
{
        if(_fDuration >= 0.0f)
        {
                m_pTarget       = _pTarget;
                m_iType         = _iType;
                m_fDuration     = _fDuration;
                if(m_pTarget)
                        m_ucCombinedAttributesCount = m_pTarget->_GetValuesCount(_iType);
        }
        return this;
}
static void Tween::Tween::SetWaypointsLimit (uint8 _Limit) inline static
Definition at line 46 of file Tween.h.
References s_WaypointsLimit.
        {
                s_WaypointsLimit = _Limit;
        }
Tween * Tween::Tween::Target (float _fTarget1, bool _bRelative = false)
Definition at line 172 of file Tween.cpp.
Referenced by Target().
{
        const float targets[] = {_fTarget1};
        return Target(targets, 1, _bRelative);
}
Tween * Tween::Tween::Target (float _fTarget1, float _fTarget2, bool _bRelative = false)
Definition at line 179 of file Tween.cpp.
References Target().
{
        const float targets[] = { _fTarget1, _fTarget2 };
        return Target(targets, 2, _bRelative);
}
Tween * Tween::Tween::Target (float _fTarget1, float _fTarget2, float _fTarget3, bool _bRelative = false)
Definition at line 186 of file Tween.cpp.
References Target().
{
        const float targets[] = { _fTarget1, _fTarget2, _fTarget3 };
        return Target(targets, 3, _bRelative);
}
Tween * Tween::Tween::Target (const float * _fTargets, int _iTargetCount, bool _bRelative = false)
Definition at line 193 of file Tween.cpp.
References Tween::BaseTween::bIsInit(), m_bIsRelative, m_fStartValues, m_fTargetValues, m_ucCombinedAttributesCount, and TWEEN_ASSERT.
{
        TWEEN_ASSERT(m_ucCombinedAttributesCount != 0, "You should call setup before setting targets");
        TWEEN_ASSERT(_iTargetCount == m_ucCombinedAttributesCount, "Target number is not the same as the start values, you should have %d targets", m_ucCombinedAttributesCount);
        m_bIsRelative = _bRelative;
        m_fTargetValues.clear();
        if(!_bRelative)
        {
                for(int i=0; i < _iTargetCount; i++)
                        m_fTargetValues.push_back(_fTargets[i] );
        }
        else
        {
                for(int i=0; i < _iTargetCount; i++)
                {
                        float fTarget =  bIsInit() ? _fTargets[i] + m_fStartValues[i] : _fTargets[i];
                        m_fTargetValues.push_back(fTarget);
                }
        }
        return this;
}
Tween * Tween::Tween::To (ITweenable * _pTarget, int _iType, float _fDuration) static
Definition at line 96 of file Tween.cpp.
References Tween::Pool< T >::Get(), s_pDefaultEquation, and s_Pool.
Referenced by From().
{
        Tween* pTween = s_Pool.Get();
        if(pTween)
        {
                pTween->Setup(_pTarget, _iType, _fDuration)->Ease(s_pDefaultEquation);
        }
        return pTween;
}
Tween * Tween::Tween::Waypoint (float _fTarget1)
Definition at line 218 of file Tween.cpp.
Referenced by Waypoint().
{
        const float waypoints[] = { _fTarget1 };
        return Waypoint(waypoints, 1);
}
Tween * Tween::Tween::Waypoint (float _fTarget1, float _fTarget2)
Definition at line 225 of file Tween.cpp.
References Waypoint().
{
        const float waypoints[] = { _fTarget1, _fTarget2 };
        return Waypoint(waypoints, 2);
}
Tween * Tween::Tween::Waypoint (float _fTarget1, float _fTarget2, float _fTarget3)
Definition at line 232 of file Tween.cpp.
References Waypoint().
{
        const float waypoints[] = { _fTarget1, _fTarget2, _fTarget3 };
        return Waypoint(waypoints, 3);
}
Tween * Tween::Tween::Waypoint (const float * _fTargets, int _iTargetCount)
Definition at line 239 of file Tween.cpp.
References m_fWaypoints, and m_ucWaypointsCount.
{
        for(int i=0; i < _iTargetCount; i++)
                m_fWaypoints.push_back(_fTargets[i] );
        ++m_ucWaypointsCount;
        return this;
}
Friends And Related Function Documentation
friend class Pool< Tween > friend
Definition at line 31 of file Tween.h.
Member Data Documentation
const int Tween::Tween::INVALID_TYPE = -1 static protected
Definition at line 34 of file Tween.h.
Referenced by _Reset(), Call(), and Mark().
bool Tween::Tween::m_bIsFrom private
Definition at line 119 of file Tween.h.
Referenced by _InnerInitialize(), _Reset(), and SetIsFrom().
bool Tween::Tween::m_bIsRelative private
Definition at line 120 of file Tween.h.
Referenced by _InnerInitialize(), _Reset(), and Target().
std::vector<float> Tween::Tween::m_fAttributesBuffer private
Definition at line 112 of file Tween.h.
Referenced by _InnerInitialize(), _InnerUpdate(), and _Reset().
std::vector<float> Tween::Tween::m_fStartValues private
Definition at line 109 of file Tween.h.
Referenced by _ForceStartValues(), _InnerInitialize(), _InnerUpdate(), _Reset(), and Target().
std::vector<float> Tween::Tween::m_fTargetValues private
Definition at line 110 of file Tween.h.
Referenced by _ForceEndValues(), _InnerInitialize(), _InnerUpdate(), _Reset(), and Target().
std::vector<float> Tween::Tween::m_fWaypoints private
Definition at line 111 of file Tween.h.
Referenced by _InnerInitialize(), _InnerUpdate(), _Reset(), and Waypoint().
std::vector<float> Tween::Tween::m_fWaypointsBuffer private
Definition at line 113 of file Tween.h.
Referenced by _InnerInitialize(), _InnerUpdate(), and _Reset().
int Tween::Tween::m_iType private
Definition at line 104 of file Tween.h.
Referenced by _bContainsTarget(), _ForceEndValues(), _ForceStartValues(), _InnerInitialize(), _InnerUpdate(), _Reset(), GetType(), and Setup().
Easing::Easing* Tween::Tween::m_pEquation private
Definition at line 106 of file Tween.h.
Referenced by _InnerUpdate(), _Reset(), Ease(), and GetEasing().
Path::Path* Tween::Tween::m_pPath private
Definition at line 107 of file Tween.h.
Referenced by _InnerUpdate(), _Reset(), and SetPath().
ITweenable* Tween::Tween::m_pTarget private
Definition at line 105 of file Tween.h.
Referenced by _bContainsTarget(), _ForceEndValues(), _ForceStartValues(), _InnerInitialize(), _InnerUpdate(), _Reset(), GetTweenable(), and Setup().
uint8 Tween::Tween::m_ucAttributesLimit private
Definition at line 115 of file Tween.h.
uint8 Tween::Tween::m_ucCombinedAttributesCount private
Definition at line 117 of file Tween.h.
Referenced by _ForceEndValues(), _ForceStartValues(), _InnerInitialize(), _InnerUpdate(), _Reset(), Setup(), and Target().
uint8 Tween::Tween::m_ucWaypointsCount private
Definition at line 118 of file Tween.h.
Referenced by _InnerInitialize(), _InnerUpdate(), _Reset(), and Waypoint().
uint8 Tween::Tween::m_ucWaypointsLimit private
Definition at line 116 of file Tween.h.
uint8 Tween::Tween::s_AttributesLimit = 4 static protected
Definition at line 35 of file Tween.h.
Referenced by SetAttributesLimit().
Easing::Easing * Tween::Tween::s_pDefaultEquation = &(Easing::QUAD_INOUT) static protected
Definition at line 38 of file Tween.h.
Referenced by Set(), SetDefaultEquation(), and To().
Pool< Tween > Tween::Tween::s_Pool = Pool<Tween>() static protected
Definition at line 37 of file Tween.h.
Referenced by Call(), Free(), Mark(), Set(), and To().
uint8 Tween::Tween::s_WaypointsLimit = 0 static protected
Definition at line 36 of file Tween.h.
Referenced by SetWaypointsLimit().
The documentation for this class was generated from the following files:
SRC/Tween/Tween.h
SRC/Tween/Tween.cpp