TweenEngineLib: Tween::Path::CatmullRomPath Class Reference
Tween::Path::CatmullRomPath Class Reference
#include <CatmullRomPath.h>
Public Member Functions
virtual float Compute (float _t, const float *_Points, const int &_PointsCount)
Private Member Functions
float GetSplineValue (float _a, float _b, float _c, float _d, float _t)
Additional Inherited Members
Protected Member Functions inherited from Tween::Path::Path
int GetSegment (float &_t, const int &_PointsCount)
Detailed Description
Definition at line 15 of file CatmullRomPath.h.
Member Function Documentation
float Tween::Path::CatmullRomPath::Compute (float _t, const float * _Points, const int & _PointsCount) virtual
Computes the next value of the interpolation, based on its waypoints and the current progress.
Parameters
_t The progress of the interpolation, between 0 and 1. May be out of these bounds if the easing equation involves some kind of rebounds.
_Points The waypoints of the tween, from start to target values.
_PointsCount The number of valid points in the array.
Returns
The next value of the interpolation.
Implements Tween::Path::Path.
Definition at line 15 of file CatmullRomPath.cpp.
References Tween::Path::Path::GetSegment(), and GetSplineValue().
        {
                int segment = GetSegment(_t, _PointsCount);
                if (segment == 0) {
                        return GetSplineValue(_Points[0], _Points[0], _Points[1], _Points[2], _t);
                }
                if (segment == _PointsCount-2) {
                        return GetSplineValue(_Points[_PointsCount-3], _Points[_PointsCount-2], _Points[_PointsCount-1], _Points[_PointsCount-1], _t);
                }
                return GetSplineValue(_Points[segment-1], _Points[segment], _Points[segment+1], _Points[segment+2], _t);
        }
float Tween::Path::CatmullRomPath::GetSplineValue (float _a, float _b, float _c, float _d, float _t) private
Definition at line 31 of file CatmullRomPath.cpp.
Referenced by Compute().
        {
                float t1 = (_c - _a) * 0.5f;
                float t2 = (_d - _b) * 0.5f;
                float h1 = +2.0f * _t * _t * _t - 3.0f * _t * _t + 1.0f;
                float h2 = -2.0f * _t * _t * _t + 3.0f * _t * _t;
                float h3 = _t * _t * _t - 2.0f * _t * _t + _t;
                float h4 = _t * _t * _t - _t * _t;
                return _b * h1 + _c * h2 + t1 * h3 + t2 * h4;
        }
The documentation for this class was generated from the following files:
SRC/Paths/CatmullRomPath.h
SRC/Paths/CatmullRomPath.cpp